In [1]:
#import libraries
import pandas as pd
from nba_api.stats.static import players

In [3]:
rel_ids = [
    203518, 1630173, 203112, 1629121, 203500, 1628389, 1629061, 201167, 1630534, 1630583,
    202332, 200746, 1629734, 1641725, 1630234, 1628959, 1628960, 1628386, 1628443, 2754,
    1630631, 202329, 1626147, 203937, 201583, 1628387, 203507, 1628961, 203648, 2546,
    1630175, 1628384, 1627853, 2772, 201589, 1628503, 201600, 201571, 1630166, 1629028,
    1628962, 202337, 1628407, 1630641, 1628963, 1641735, 1627758, 1627735, 1631116,
    1630163, 1628366, 1628964, 1631094, 1630217, 1630625, 200826, 1631230, 203084,
    1630567, 1629628, 203115, 1629646, 1641734, 1628966, 1642419, 201587, 201573, 203382,
    203145, 1629647, 203078, 1627736, 201563, 1630699, 1641736, 201158, 1628395, 1627761,
    1627761, 1627733, 1631262, 1629541, 202722, 201976, 1630180, 1630189, 203920,
    1628444, 1629048, 1641931, 202687, 202357, 1641710, 1641778, 204028, 1628469, 202339, 
    1629833,1628417, 203505, 1631205, 203992, 202711, 101106, 1629626, 1628413, 1629716, 
    1630195, 1627762, 1641737, 1629648, 1629067, 1626164, 202344, 1630527, 1628449, 
    1630547, 1631123, 1628968, 1629065, 202340, 1628396, 1631103, 1631128, 1629649, 
    201147, 1641779, 1628969, 1628970, 1628578, 1629052, 1629151, 1627763, 201166, 
    1629717, 1628415, 202705, 1631232, 1626148, 201628, 1628971, 1627759, 1631112,
    1641738, 203485, 203900, 1629650, 1628425, 1630535, 1629718, 1630602, 1628972,
    1628973, 1627852, 1629091, 1628418, 1641723, 203493, 203504, 202692, 1629126, 
    1630215, 202710, 1631219, 202779, 1641824, 203998, 1629719, 1631288, 101181, 203484,
    1641739, 1630267, 203477, 1629962, 203991, 1630176, 1642382, 1642267, 201960, 1642269,
    1628975, 1713, 1628976, 203487, 1630618, 1627936, 201956, 1642264, 1630658, 1626161, 
    1628505, 1628463, 201596, 1630577, 1630551, 1631113, 2199, 201163, 1629147, 1629597, 
    1629185, 1642279, 1627737, 1642353, 1631108, 1630528, 1631321, 1629109, 203546, 
    1641740, 1629634, 203903, 1629651, 1629598, 1628499, 1642270, 1641730, 1629599, 
    1642268, 1628381, 1628380, 1627858, 201954, 2555, 1629045, 201144, 1626192, 1626188, 
    1629076, 1628429, 1641645, 204022, 1630536, 1627856, 1641731, 1641741, 202326, 203496, 
    203459, 1628470, 1642384, 2037, 202348, 1628249, 203109, 1629633, 1630595, 201967, 
    203552, 201939, 1642359, 1630700, 203584, 1642368, 1630268, 203076, 1627738, 202334, 
    1631098, 1629056, 1631120, 1630620, 201942, 1630466, 203473, 1626155, 1627098, 
    1629116, 203521, 2736, 1642484, 1629094, 1628978, 1631217, 1629603, 1627767, 1628977, 
    1641711, 203476, 1631172, 1642265, 203915, 1629029, 1628416, 1629652, 1630245, 
    1628422, 1629653, 1629635, 1630288, 1628495, 1628408, 201609, 1630929, 203580, 
    203083, 1630537, 1642505, 201162, 1630561, 1627739, 1642346, 201142, 1631105, 1628979,
    1631106, 204067, 1641744, 1630162, 1629035, 1642399, 1642348, 1630556, 1629053, 
    1629604, 1627740, 201961, 1631165, 203954, 203898, 203516, 1629234, 1628980, 1628393,
    202379, 201936, 1641787, 203957, 1629605, 202702, 202324, 1627770, 1626245, 101109, 
    1628390, 1628981, 1627812, 1642271, 1627827, 1630238, 1641745, 1642280, 1630201, 
    1631323, 1627854, 1630259, 1630235, 203095, 1628368, 204025, 1626187, 1628982, 202690, 
    202683, 1642402, 1631241, 101112, 1641788, 1628365, 1641847, 1642277, 1629117, 
    1629655, 201568, 204038, 1629636, 1628656, 1630585, 1630586, 1630568, 201188, 2200, 
    200752, 1641718, 1642273, 202331, 1627875, 1626780, 201959, 1630581, 1628385, 1628983, 
    1630264, 1631221, 1630273, 1631367, 1938, 203497, 1629164, 1630692, 203932, 201569, 
    101162, 1641789, 1628984, 1626203, 203924, 1626170, 1629055, 1627982, 1630564, 
    1631260, 201980, 203110, 101123, 203210, 1630224, 1629750, 201145, 1630182, 1631100, 
    201933, 1629656, 1629741, 1631338, 1631243, 1629657, 1629060, 1630204, 1630169, 
    1628985, 1629743, 1630221, 1641790, 1627772, 1630181, 203501, 201935, 1630702, 
    1641989, 203090, 1629607, 1631199, 1626149, 2734, 203914, 203925, 1630284, 202699, 
    1626151, 1626150, 1627885, 1628404, 1628392, 2617, 1630573, 1641722, 1629637, 1630165, 
    1628502, 202330, 203687, 1630703, 1641707, 1627988, 203089, 1629608, 1627823, 1626195, 
    1629639, 1628987, 1626209, 1628439, 1627741, 1629312, 201588, 1630792, 203524, 
    1626199, 1630207, 1629658, 1628988, 201950, 203200, 204066, 1641842, 1626178, 1626158, 
    1631096, 203918, 1641720, 203816, 201143, 1629659, 1627863, 1631216, 2730, 1641724, 
    1630210, 1629739, 1631309, 1628989, 203962, 1630643, 1630190, 1630574, 1629353, 
    1630624, 1629631, 1626154, 1630562, 1628990, 1630538, 201586, 1642345, 2738, 101141, 
    204060, 201281, 1627742, 1631127, 202681, 1628371, 1631093, 1628411, 101127, 1628935, 
    1627743, 1628402, 1641713, 1630543, 1628367, 1628382, 1631245, 202704, 1641748, 
    1628991, 1631218, 1642355, 2544, 1628455, 1631170, 2744, 1628518, 2210, 1629610, 
    1641998, 1642450, 203098, 201943, 201973, 1629660, 1630198, 1642358, 1628993, 101161, 
    1629168, 1627744, 1629661, 1626177, 1630525, 1630552, 201949, 2207, 1629640, 1630553, 
    1642352, 1641749, 1626169, 204020, 202325, 203999, 1630637, 1641732, 1627745, 1641794, 
    1630529, 1642403, 1627883, 1629203, 1630539, 1630222, 1642461, 203093, 1630200, 
    1626145, 1627884, 201599, 202709, 1631107, 1630548, 1629662, 1626163, 1642530, 
    1631211, 1628379, 1631117, 1630296, 203077, 203930, 1628994, 1629663, 1630557,
    1628467, 1641752, 1642261, 202688, 1630233, 1628995, 1642278, 1631132, 1629723, 
    1627788, 1628436, 2594, 201585, 1630249, 1629083, 1630228, 1629066, 1628398, 1627851,
    1631222, 203897, 1627746, 1630237, 203087, 1629111, 1629641, 203499, 1641796, 203530,
    1629724, 1630639, 1627774, 1627747, 1628388, 1629665, 201584, 1627814, 1630240, 
    1627215, 203458, 202695, 203086, 1642502, 202720, 1641721, 1630575, 1630184, 1630604, 
    202732, 203081, 202391, 1629642, 1641726, 1630587, 1641753, 2733, 1631254, 1626172, 
    201572, 201577, 1629712, 201567, 200768, 1628070, 203564, 1630994, 1641754, 1627789, 
    1628399, 1626168, 203159, 202714, 1629133, 1629122, 203705, 101133, 1627748, 1630177, 
    1630572, 1629611, 1630544, 1630185, 1626246, 1628374, 1630230, 1628997, 1628998, 
    1626185, 1641798, 1629725, 1630231, 1629103, 1631213, 1628412, 1628999, 1629726, 
    1628493, 1631097, 1631255, 202083, 1630178, 1630219, 201601, 203949, 1630540, 1642272, 
    1627775, 1630644, 203468, 204456, 1628571, 1641755, 1626191, 1630183, 1629667, 203926, 
    1630253, 201580, 1631121, 203585, 1628035, 1629162, 203463, 203895, 201177, 1629098, 
    201975, 1626257, 1629740, 1629001, 1630241, 1629002, 203995, 1626175, 203114, 101139, 
    1641706, 203121, 1641801, 1641757, 1631159, 1626259, 201988, 200794, 1629003, 1631303, 
    1642434, 1631169, 202703, 1642274, 1642349, 1630558, 1628378, 1628513, 1630596, 
    1630600, 1642367, 1629690, 1631320, 1628370, 202328, 1626242, 1630541, 1629875, 
    1629760, 1628500, 202734, 1631386, 1631111, 1629630, 203961, 1629752, 1628537, 202693, 
    1628420, 202694, 202700, 1628405, 202389, 1626144, 203498, 1628539, 204098, 1630530, 
    1627749, 1627750, 1631099, 1631200, 1629058, 203488, 1629004, 1627846, 1631250, 
    1626204, 203894, 2749, 1629614, 1630612, 2403, 1630174, 203526, 1641803, 1627777,
    1630227, 1630192, 201149, 203457, 203512, 1629669, 1717, 1628373, 1629134, 203263, 
    203994, 1628021, 1629670, 203948, 1626220, 203124, 1628400, 2731, 1626143, 1629643, 
    1629059, 1629006, 1630168, 1630171, 1629644, 203506, 1642439, 203482, 1630647, 1629671,
    1627778, 1626224, 1630187, 1626162, 1629745, 2585, 1627779, 1627834, 202951, 203953, 
    2225, 202718, 1629672, 1628394, 202335, 1628383, 203464, 101108, 203940, 1626166, 
    203901, 1627780, 203658, 2570, 1629617, 1628409, 1641809, 1641763, 1629618, 1630691, 
    1629033, 1630590, 1631342, 1627850, 203486, 203101, 1641764, 1627751, 1629738, 1630197, 
    202347, 1630582, 1629673, 1629007, 1641854, 1629645, 1629008, 203490, 1626171, 204001, 
    1642366, 1630695, 203939, 1629619, 1626181, 1627816, 1630554, 1630563, 1627752, 
    1630202, 1641765, 1642389, 1628681, 1627817, 1630243, 1629674, 1630193, 1631311, 
    1628397, 1630186, 1626184, 203944, 2216, 1641871, 1630559, 1629729, 1629629, 200755, 
    1628432, 1630194, 203186, 1642024, 1641810, 1629675, 1629244, 1631197, 1630208, 
    1626196, 1627781, 1630203, 1642258, 203085, 1641857, 203460, 1628421, 1629130, 1629010, 
    1629011, 1631115, 203922, 1630526, 1629676, 1631223, 1631157, 200765, 201565, 203082, 
    1626179, 201937, 1641712, 1626156, 1630346, 1627734, 1642275, 1629677, 1629102, 203960, 
    1631257, 1641766, 1630611, 1642259, 1630846, 1631204, 203107, 1630648, 1631248, 1629678, 
    203471, 203118, 1630206, 1631220, 200757, 1627782, 1630578, 1641729, 201196, 1629012, 
    1629013, 1630545, 1630549, 1631101, 1629621, 1642347, 1641767, 1642263, 202697, 1627783, 
    202918, 1629735, 1627732, 203613, 1628424, 1630250, 1629014, 1642354, 1630579, 202713, 
    1629686, 1641771, 1629346, 1630606, 203935, 1630696, 202397, 2747, 1630188, 201160, 
    2746, 1631173, 1642449, 1641890, 1629015, 1628372, 1631095, 1641733, 1630270, 203503, 
    1631110, 1629034, 201578, 1629016, 1642285, 1630311, 1630531, 1630199, 203917, 202362, 
    1641815, 1630205, 1630191, 204065, 202933, 1631124, 1629622, 1630591, 1628410, 1628403, 
    1631306, 1630256, 1628369, 1627819, 1630678, 201952, 203104, 203141, 202066, 1628462, 
    1629123, 1631207, 1891, 1630179, 1628464, 1630271, 1630560, 202738, 1629017, 202498, 
    1629744, 1641708, 1641709, 202691, 202684, 1630550, 1628414, 1629680, 1629681, 1630214, 
    1630225, 201229, 1631210, 1630167, 1629308, 1626253, 1626157, 1642422, 1631247, 1629018, 
    1629019, 1631131, 200782, 1629730, 202323, 1626167, 1641816, 1642281, 202327, 1627755, 
    1630649, 1627784, 202685, 1627756, 1627832, 1629020, 2760, 1630170, 1626173, 1628426, 
    1629216, 203943, 1641774, 202696, 1629731, 2548, 1630532, 1629021, 1630688, 203079, 
    1631133, 1641716, 202689, 1629022, 202322, 1641717, 1630811, 1627820, 1641775, 1642266, 
    1628476, 202954, 1642276, 203933, 1627395, 1629023, 1630613, 1631102, 1629139, 1629682, 
    1630322, 1630570, 1641817, 1628778, 1631212, 204037, 1629683, 1627821, 1627362, 1642377, 
    1629118, 1641705, 1631104, 2561, 201566, 1629632, 1628401, 1631298, 1627855, 1628510,
    1641727, 1627785, 202355, 1641715, 1630580, 1630598, 203952, 1629623, 2863, 1626210, 
    1631214, 1630314, 203710, 1642262, 202682, 1631495, 1629684, 1631114, 1631119, 1629140, 
    1629026, 101150, 1642013, 1631109, 101107, 1631466, 1630172, 1627786, 1630533, 1629057, 
    1631246, 1628430, 1629627, 1628391, 1630592, 1629685, 1626159, 1630216, 1630164, 203481, 
    203489, 1631209, 1626174, 1630218, 201148, 1626153, 1630589, 1630593, 1629625, 1627824, 
    1628221, 203923, 1626202, 201156, 201152, 1629027, 1630209, 203469, 203092, 1627753,
    1627835, 1627790, 1627826, 1641783, 1628427, 203967
]

In [5]:
#get full list of nba players from NBA API, filtered for players with IDs that are relevant, and put their names and IDs in a DataFrame
#these IDs identify players for the NBA API
#relevant players played in the regular seasons 2017-18 to 2024-25
athletes = players.get_players()
ls = [[athlete['id'], athlete['full_name']] for athlete in athletes if athlete['id'] in rel_ids]
print(len(ls))

1199

In [7]:
nba_api = pd.DataFrame(ls, columns=['id', 'full_name'])
nba_api.head()

        id         full_name
0   203518      Alex Abrines
1  1630173  Precious Achiuwa
2   203112        Quincy Acy
3  1629121      Jaylen Adams
4   203500      Steven Adams

In [9]:
#load DataFrame of information saved from the sportsdataverse/hoopR repository
path = 'C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\espn_athlete_ids.csv'
hoopR = pd.read_csv(path)
hoopR.head()

   athlete_id athlete_display_name
0         136         Vince Carter
1         165       Jamal Crawford
2         272        Manu Ginobili
3         609        Dirk Nowitzki
4         841          Jason Terry

In [11]:
#check for athletes that appear twice in nba_api (the DataFrame) ... there are none
def check_dupes(ls):
    running_tally = []
    dups = []

    for athlete in ls:
        if athlete in running_tally:
            dups.append(athlete)
        running_tally.append(athlete)
    return dups

print(check_dupes(nba_api['full_name']))

[]

In [13]:
#check for athletes that appear twice in espn (the DataFrame)
print(check_dupes(hoopR['athlete_display_name']))

['Isaiah Canaan', 'Mitchell Creek', 'Greg Monroe', 'Ray Spalding', 'Corey Brewer', 'John Jenkins', 'Tahjere McCall', 'Henry Ellenson', 'Daryl Macon', 'Wayne Selden']

In [15]:
#find the indices that have the duplicated athletes in hoopR DataFrame
dupes = check_dupes(hoopR['athlete_display_name'])
i = 0
dup_indices = []
for athlete in hoopR['athlete_display_name']:
    if athlete in dupes:
        dup_indices.append(i)
    i += 1

print(dup_indices)
print('number of duped athletes: ', len(dupes))
print('number of indices including duped athletes: ', len(dup_indices), '(this number should be double or more...)')

[60, 144, 208, 265, 409, 462, 612, 635, 750, 829, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1208, 1280]
number of duped athletes:  10
number of indices including duped athletes:  20 (this number should be double or more...)

In [17]:
#this just makes it easy to visualize
hoopR.iloc[dup_indices, 1].sort_values()

60        Corey Brewer
1026      Corey Brewer
750        Daryl Macon
1208       Daryl Macon
144        Greg Monroe
1024       Greg Monroe
1029    Henry Ellenson
612     Henry Ellenson
265      Isaiah Canaan
1022     Isaiah Canaan
208       John Jenkins
1027      John Jenkins
829     Mitchell Creek
1023    Mitchell Creek
1025      Ray Spalding
635       Ray Spalding
1028    Tahjere McCall
409     Tahjere McCall
462       Wayne Selden
1280      Wayne Selden
Name: athlete_display_name, dtype: object

In [19]:
#separate the records in hoopR into two DataFrames so that athletes with multiple IDs can be handled separately
hoopR_no_dupes = hoopR.drop(dup_indices)
hoopR_no_dupes.reset_index(drop=True, inplace=True)
hoopR_dupes = hoopR.loc[dup_indices]
hoopR_dupes.reset_index(drop=True, inplace=True)

In [21]:
#check that 20 records are in the dupes DataFrame and the other 1316 are in the no_dupes DataFrame
print('shape of hoopR: ', hoopR.shape)
print('shape of hoopR_no_dupes: ', hoopR_no_dupes.shape)
print('shape of hoopR_dupes: ', hoopR_dupes.shape)

shape of hoopR:  (1336, 2)
shape of hoopR_no_dupes:  (1316, 2)
shape of hoopR_dupes:  (20, 2)

In [23]:
#check if the athletes that are duplicated in hoopR are represented in the nba_api DataFrame ... 9/10 are represented.
dupes_in_nba_api = []
for athlete in hoopR_dupes['athlete_display_name'].unique():
    if athlete in nba_api['full_name'].values:
        dupes_in_nba_api.append(athlete)

print(dupes_in_nba_api)

['Corey Brewer', 'Greg Monroe', 'John Jenkins', 'Isaiah Canaan', 'Wayne Selden', 'Henry Ellenson', 'Ray Spalding', 'Daryl Macon', 'Mitchell Creek']

In [25]:
#display the name of the athlete not represented in the nba_api Dataframe and duplicated in the hoopR DataFrame
for athlete in hoopR_dupes['athlete_display_name'].unique():
    if athlete not in dupes_in_nba_api:
        print(athlete)

Tahjere McCall

*Tahjere McCall is the only guy duplicated in the ESPN data that doesn't show up in nba_api data; makes sense because he only ever played one game in the NBA according to sportsreference.com

In [27]:
#find the indices of the athletes duplicated in the hoopR DataFrame and separate the nba_api DataFrame by these athletes
i = 0
dup_indices = []
for name in nba_api['full_name']:
    if name in hoopR_dupes['athlete_display_name'].unique():
        dup_indices.append(i)
    i += 1
print(dup_indices)

nba_api_no_dupes = nba_api.drop(dup_indices)
nba_api_no_dupes.reset_index(drop=True, inplace=True)
nba_api_dupes = nba_api.loc[dup_indices]
nba_api_dupes.reset_index(drop=True, inplace=True)

#should be a 9 record difference in number of rows between the two new DataFrames
print('shape of nba_api: ', nba_api.shape)
print('shape of nba_api_no_dupes: ', nba_api_no_dupes.shape)
print('shape of nba_api_dupes: ', nba_api_dupes.shape)

[124, 172, 243, 315, 538, 665, 753, 958, 1004]
shape of nba_api:  (1199, 2)
shape of nba_api_no_dupes:  (1190, 2)
shape of nba_api_dupes:  (9, 2)

In [29]:
#lets find the common names in both and examine the names that are not matches
name_matches = []
for name in nba_api_no_dupes['full_name']:
    if name in hoopR_no_dupes['athlete_display_name'].values:
        name_matches.append(name)

print('shape of nba_api_no_dupes: ', nba_api_no_dupes.shape)
print('shape of hoopR_no_dupes: ', hoopR_no_dupes.shape)
print('number of matches: ', len(name_matches))

shape of nba_api_no_dupes:  (1190, 2)
shape of hoopR_no_dupes:  (1316, 2)
number of matches:  1165

In [31]:
#list the names that appear exlusively in each DataFrame

#NAND:nba_api_no_dupes
nand_uniques = []
for name in nba_api_no_dupes['full_name']:
    if name not in name_matches:
        nand_uniques.append(name)
#HRND:espn_no_dupes
hrnd_uniques = []
for athlete in hoopR_no_dupes['athlete_display_name']:
    if athlete not in name_matches:
        hrnd_uniques.append(athlete)

print('nba_api unqiue athletes: ', nand_uniques)
print('hoopR unique athltes: ', hrnd_uniques)

nba_api unqiue athletes:  ['Bogdan Bogdanović', 'Bojan Bogdanović', 'Carlton Carrington', 'Luka Dončić', 'Danté Exum', 'Billy Garrett', 'Nikola Jokić', 'Nikola Jović', 'Vít Krejčí', 'Boban Marjanović', 'Karlo Matković', 'Vasilije Micić', 'Monté Morris', 'Ruben Nembhard Jr.', 'Nene', 'Jusuf Nurkić', 'Kristaps Porziņģis', 'Cam Reynolds', 'Tidjane Salaün', 'Alexandre Sarr', 'Dennis Schröder', 'Jonas Valančiūnas', 'Nikola Vučević', 'Vlatko Čančar', 'Dario Šarić']
hoopR unique athltes:  ['Nene ', 'Brandon Rush', 'Bojan Bogdanovic', 'Ty Lawson', 'Boban Marjanovic', 'Jimmy Butler III', 'Jonas Valanciunas', 'Nikola Vucevic', 'Jacob Pullen', 'Omari Johnson', 'Trey McKinney-Jones', 'Jamil Wilson', 'DJ Stephens', 'Reggie Bullock', 'Carrick Felix', 'Richard Solomon', 'Jordan Sibert', 'Kevin Pangos', 'Sheldon Mac', 'Greg Whittington', 'Levi Randolph', 'Keifer Sykes', "Sir'Dominic Pointer", 'Jameel Warney', 'AJ Hammons', 'Matt Williams Jr.', 'Craig Sword', 'Jacob Wiley', 'Stanton Kidd', 'Dusty Hannahs', 'Dario Saric', 'Dennis Schroder', 'Bogdan Bogdanovic', 'Cameron Reynolds', 'Vince Shamar Hunter', 'Xavier Rathan-Mayes', 'Cat Barber', 'Mike Young', 'London Perrantes', 'Monte Morris', 'Billy Garrett Jr.', 'Zach Lofton', 'Paris Bass', 'Rondae Hollis Jefferson', 'Eric Mika', 'Dante Exum', 'Jusuf Nurkic', 'Kristaps Porzingis', 'Vasilije Micic', 'Nikola Jokic', 'Keenan Evans', 'Jaysean Paige', 'Trevon Bluiett', 'Dakota Mathias', 'Gian Clavell', 'Justin Tillman', 'DeVaughn Akoon-Purcell', 'Trayvon Palmer', 'Petr Cornelie', 'Dimitrios Agravanis', 'Malik Newman', 'Aric Holman', 'Chance Comanche', 'Jarrell Brantley', 'Kaiser Gates', 'Justin James', 'Rob Edwards', 'Robert Franks', 'Cameron Oliver', 'Tyler Hall', 'O.G. Anunoby', 'Isaiah Briscoe', 'Malik Ellison', 'Luka Doncic', 'Justin Robinson', 'Tyler Davis', 'Ahmad Caver', 'Kylor Kelley', 'Cody Demps', 'Javin DeLaurier', 'Shamorie Ponds', 'Omari Rasulala Spellman', 'Hassani Gravett', 'Cameron McGriff', 'Zavier Simpson', 'Jon Teske', 'Aleem Ford', 'Jarron Cumberland', 'JaQuori McLaughlin', 'Zach Norvell Jr.', 'DeJon Jarreau', 'Jackson Rowe', 'Jalen Harris', 'Ade Murkey', 'Vlatko Cancar', 'Luca Vildoza', 'Yakuba Ouattara', 'MJ Walker', 'RJ Nembhard Jr.', 'Nickeil Alexander-Walker', 'Jalen Crutcher', 'Izaiah Brockington', 'Ethan Thompson', 'Chris Smith', 'Will Magnay', 'Shaq Buchanan', 'Joel Ayayi', "Sir'Jabari Rice", 'Emanuel Terry', 'Dexter Dennis', 'Erik Stevenson', 'Jaime Echenique', 'DJ Stewart', 'Miles Norris', 'Timmy Allen', 'Aaron Henry', 'Nathan Mensah', 'Taevion Kinsey', 'Markquis Nowell', 'Jaylen Sims', 'Filip Petrusev', 'Cameron Parker', 'Daulton Hommes', 'Drew Timme', 'Damion Baugh', 'Karim Mane', 'Tyson Etienne', 'Yuri Collins', 'Jahmir Young', 'Marcus Bagley', 'Charles Bediako', 'Vit Krejci', 'Boo Buie', 'Dmytro Skapintsev', 'Georgios Kalaitzakis', 'Jordan Hall', "D'Moi Hodge", 'Trevon Scott', 'Michael Foster Jr.', 'Bub Carrington', 'Malcolm Cazalon', 'Taran Armstrong', 'Phillip Wheeler', 'Nikola Jovic', 'Karlo Matkovic', 'Jaylin Galloway', "Nae'Qwan Tomlin", 'Yongxi Cui', 'Alex Sarr', 'Maozinha Pereira', 'Tidjane Salaun']

In [33]:
#list the indices for each DataFrame where the exclusive names appear so they can be isolated into new DataFrames
i = 0
nand_unique_indices = []
for name in nba_api_no_dupes['full_name']:
    if name in nand_uniques:
        nand_unique_indices.append(i)
    i += 1

i = 0
hrnd_unique_indices = []
for name in hoopR_no_dupes['athlete_display_name']:
    if name in hrnd_uniques:
        hrnd_unique_indices.append(i)
    i += 1

print('nba_api_no_dupes unique athletes: ', nand_unique_indices)
print('hoopR_no_dupes unique athlete IDs: ', hrnd_unique_indices)

nba_api_no_dupes unique athletes:  [100, 101, 175, 279, 323, 362, 556, 574, 601, 669, 685, 719, 760, 783, 784, 799, 868, 903, 932, 939, 946, 1066, 1077, 1188, 1189]
hoopR_no_dupes unique athlete IDs:  [11, 98, 103, 120, 154, 161, 185, 186, 229, 231, 239, 252, 254, 276, 291, 293, 311, 332, 335, 336, 343, 349, 352, 360, 393, 402, 403, 411, 412, 420, 424, 425, 427, 437, 438, 442, 444, 447, 451, 454, 460, 463, 467, 474, 493, 504, 506, 507, 508, 510, 523, 525, 548, 558, 560, 574, 575, 586, 602, 603, 612, 613, 622, 637, 641, 650, 654, 665, 669, 679, 680, 685, 690, 692, 693, 695, 697, 699, 708, 714, 734, 736, 740, 752, 762, 763, 772, 781, 783, 787, 796, 799, 801, 807, 818, 819, 822, 831, 842, 854, 873, 877, 881, 883, 894, 899, 901, 903, 912, 937, 938, 939, 944, 963, 971, 978, 985, 990, 991, 992, 995, 1004, 1019, 1034, 1044, 1081, 1108, 1111, 1115, 1119, 1144, 1149, 1167, 1185, 1192, 1224, 1236, 1239, 1247, 1250, 1254, 1263, 1268, 1272, 1275, 1281, 1297, 1303, 1305, 1311, 1313]

In [35]:
#make two new DataFrames from nba_api_no_dupes for names that either match names in the hoopR_no_dupes or are exclusive
nand_match = nba_api_no_dupes.drop(nand_unique_indices) #nand_match meaning nba api no duplicate matching (with hoopR_no_dupes) records
nand_match.reset_index(drop=True, inplace=True)
nand_u = nba_api_no_dupes.loc[nand_unique_indices] #nand_u meaning nba api no duplicate unique records
nand_u.reset_index(drop=True, inplace=True)

#should say that of 1190 records, 1165 went to nand_match and 25 went to nand_u
print('shape of nba_api_no_dupes: ', nba_api_no_dupes.shape)
print('shape of nand_match: ', nand_match.shape)
print('shape of nand_u: ', nand_u.shape)

shape of nba_api_no_dupes:  (1190, 2)
shape of nand_match:  (1165, 2)
shape of nand_u:  (25, 2)

In [37]:
#same separation of DataFrame by whether or not names match the nba_api_no_dupes DataFrame
hrnd_match = hoopR_no_dupes.drop(hrnd_unique_indices)
hrnd_match.reset_index(drop=True, inplace=True)
hrnd_u = hoopR_no_dupes.loc[hrnd_unique_indices]
hrnd_u.reset_index(drop=True, inplace=True)

#should separate 1316 records into 1165 to hrnd_match and 151 to hrnd_u
print('shape of hoopR_no_dupes: ', hoopR_no_dupes.shape)
print('shape of hrnd_match: ', hrnd_match.shape)
print('shape of hrnd_u: ', hrnd_u.shape)

shape of hoopR_no_dupes:  (1316, 2)
shape of hrnd_match:  (1165, 2)
shape of hrnd_u:  (151, 2)

In [39]:
#for next block of code
print(nand_u.columns)
print(hrnd_u.columns)

Index(['id', 'full_name'], dtype='object')
Index(['athlete_id', 'athlete_display_name'], dtype='object')

In [41]:
#reformat DataFrames and export to excel for analysis of names exclusive to each DataFrame
nand_u.rename(columns={'id':'nID', 'full_name':'nName'}, inplace=True)
nand_u.sort_values(by='nName', inplace=True)
nand_u['nIndex'] = nand_u.index

hrnd_u.rename(columns={'athlete_id':'eID', 'athlete_display_name':'eName'}, inplace=True)
hrnd_u.sort_values(by='eName', inplace=True)
hrnd_u['eIndex'] = hrnd_u.index

#nand_u.to_excel('C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\nba_api_uniques.xlsx')
#hrnd_u.to_excel('C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\espn_uniques.xlsx')

**Data off to Excel for analysis...**

In [44]:
#in the mean time I found this:
hoopR_no_dupes.iloc[680:682,]

     athlete_id athlete_display_name
680     3934719         O.G. Anunoby
681     3934719           OG Anunoby

In [46]:
#find all IDs that are repeated and represent multiple names, get the indices where the IDs are present, and show duplicate records
tally = []
duped_IDs = []
i = 0
for idx in hoopR_no_dupes['athlete_id']:
    if idx not in tally:
        tally.append(idx)
    else:
        duped_IDs.append(idx)

i = 0
indices = []
for athlete_id in hoopR_no_dupes['athlete_id']:
    if athlete_id in duped_IDs:
        indices.append(i)
    i += 1

hoopR_no_dupes.iloc[indices,]

     athlete_id     athlete_display_name
160        6430             Jimmy Butler
161        6430         Jimmy Butler III
276     2528779           Reggie Bullock
277     2528779       Reggie Bullock Jr.
473     3064291  Rondae Hollis-Jefferson
474     3064291  Rondae Hollis Jefferson
680     3934719             O.G. Anunoby
681     3934719               OG Anunoby
735     4065836           Omari Spellman
736     4065836  Omari Rasulala Spellman

In [48]:
#rule out that the same thing is happening in nba_api_no_dupes
tally = []
dupes = []
for idx in nba_api_no_dupes['id']:
    if idx not in tally:
        tally.append(idx)
    else:
        dupes.append(idx)

print(len(dupes)) #should print 0 if none IDs are not duplicated

0

In [50]:
#rule out that there are duplicate names in nba_api_no_dupes
tally = []
dupes = []
for idx in nba_api_no_dupes['full_name']:
    if idx not in tally:
        tally.append(idx)
    else:
        dupes.append(idx)

print(len(dupes)) #should print 0 if none IDs are not duplicated

0

**Data Analysis in Excel Complete**
Conclusion: of the 151 hoopR athletes and 25 nba_api athletes mismatched, 5 were duplicates of matches (shown 3 cells above), 
25 were misspelled names, and 121 will be excluded (78 didn't play more than 10 games in 8 regular seasons)
Solution: change the names of the 25 misspelled names to the spelling in the hoopR DataFrame,

In [52]:
#start the ID-name matching with the perfect name matches in DataFrames nand_match and hrnd_match
match_IDs = hrnd_match.join(nand_match.set_index('full_name'), on='athlete_display_name')
match_IDs.head()

   athlete_id athlete_display_name    id
0         136         Vince Carter  1713
1         165       Jamal Crawford  2037
2         272        Manu Ginobili  1938
3         609        Dirk Nowitzki  1717
4         841          Jason Terry  1891

In [54]:
match_IDs.rename(columns={'athlete_id':'hoopR_ID', 'athlete_display_name':'athlete', 'id':'nba_api_ID'}, inplace=True)
match_IDs.head()

   hoopR_ID         athlete  nba_api_ID
0       136    Vince Carter        1713
1       165  Jamal Crawford        2037
2       272   Manu Ginobili        1938
3       609   Dirk Nowitzki        1717
4       841     Jason Terry        1891

In [56]:
match_IDs.shape

(1165, 3)

In [58]:
"""
160	6430	Jimmy Butler
161	6430	Jimmy Butler III
276	2528779	Reggie Bullock
277	2528779	Reggie Bullock Jr.
473	3064291	Rondae Hollis-Jefferson
474	3064291	Rondae Hollis Jefferson
680	3934719	O.G. Anunoby
681	3934719	OG Anunoby
735	4065836	Omari Spellman
736	4065836	Omari Rasulala Spellman
From the table above I identified these IDs as representing two names.
1. using the excel analysis I found that these names...
    Jimmy Butler, Reggie Bullock Jr., Rondae Hollis-Jefferson, OG Anunoby, Omari Spellman
    ...are names in the nba_api DataFrame.
2. Analysis in investigate_id_duplicates.ipynb I found that these changes needed to be made in the hoopR data so that the names are consistent 
across all records for players and under one ID and that the name matches the name in nba_api DataFrame...
    a. Jimmy Butler III to Jimmy Butler
    b. Reggie Bullock to Reggie Bullock Jr.
    c. Rondae Hollis Jefferson to Rondae Hollis-Jefferson
    d. O.G. Anunoby to OG Anunoby
    e. Omari Rasulala Spellman to Omari Spellman
3. No changes need to be made to the match_ID DataFrame as only the names in nba_api are in the match_ID DataFrame. The alternate names for
the same ID can just be dropped for now but referenced later for modifying the hoopR data.
"""

'\n160\t6430\tJimmy Butler\n161\t6430\tJimmy Butler III\n276\t2528779\tReggie Bullock\n277\t2528779\tReggie Bullock Jr.\n473\t3064291\tRondae Hollis-Jefferson\n474\t3064291\tRondae Hollis Jefferson\n680\t3934719\tO.G. Anunoby\n681\t3934719\tOG Anunoby\n735\t4065836\tOmari Spellman\n736\t4065836\tOmari Rasulala Spellman\nFrom the table above I identified these IDs as representing two names.\n1. using the excel analysis I found that these names...\n    Jimmy Butler, Reggie Bullock Jr., Rondae Hollis-Jefferson, OG Anunoby, Omari Spellman\n    ...are names in the nba_api DataFrame.\n2. Analysis in investigate_id_duplicates.ipynb I found that these changes needed to be made in the hoopR data so that the names are consistent \nacross all records for players and under one ID and that the name matches the name in nba_api DataFrame...\n    a. Jimmy Butler III to Jimmy Butler\n    b. Reggie Bullock to Reggie Bullock Jr.\n    c. Rondae Hollis Jefferson to Rondae Hollis-Jefferson\n    d. O.G. Anunoby to OG Anunoby\n    e. Omari Rasulala Spellman to Omari Spellman\n3. No changes need to be made to the match_ID DataFrame as only the names in nba_api are in the match_ID DataFrame. The alternate names for\nthe same ID can just be dropped for now but referenced later for modifying the hoopR data.\n'

In [60]:
#next, match the IDs of the 9/10 athletes first identified as duplicates and concatenate them to the match_ID DataFrame
hoopR_dupes.sort_values(by='athlete_display_name')

    athlete_id athlete_display_name
0         3191         Corey Brewer
14     4415554         Corey Brewer
8      4066243          Daryl Macon
18     4610145          Daryl Macon
1         4260          Greg Monroe
12     4412680          Greg Monroe
17     4417428       Henry Ellenson
6      3906522       Henry Ellenson
3      2490589        Isaiah Canaan
10     4412182        Isaiah Canaan
2         6594         John Jenkins
15     4415789         John Jenkins
9      4236300       Mitchell Creek
11     4412474       Mitchell Creek
13     4415522         Ray Spalding
7      3908806         Ray Spalding
16     4416645       Tahjere McCall
4      2992257       Tahjere McCall
5      3059316         Wayne Selden
19     4895499         Wayne Selden

In [62]:
# drop Tahjere McCall because he was identified as missing from the nba_api DataFrame
hoopR_dupes = hoopR_dupes.drop([16, 4])
hoopR_dupes.reset_index(drop=True, inplace=True)

In [64]:
"""
I analyzed the athletes that have two different IDs in the hoopR data in investigate_name_duplicates.ipynb and found that these changes must be
made in the data and these IDs be chosen over the alternative ID...

DROP RECORDS

1. for Corey Brewer, records with player_ID 4415554 should be dropped from the hoopR data. Final ID for Corey Brewer: 3191.

2. for Daryl Macon, records with player_ID 4610145 should be dropped from the hoppR data. Final ID for Daryl Macon: 4066243.

3. for Henry Ellenson, records with the player_ID 4417428 should be dropped from the hoopR data. Final ID for Henry Ellenson: 3906522.

4. for John Jenkins, records with the player_ID 4415789 should be dropped from the hoopR data. Final ID for John Jenkins: 6594.

5. for Mitchell Creek, records with the player_ID 4412474 should be dropped from the hoopR data. Final ID for Mitchell Creek: 4236300.

6. for Isaiah  Canaan, records with the player_ID 4412182 should be dropped from the hoopR data. Final ID for Isaiah Canaan: 2490589.

MODIFY RECORDS

7. for Greg Monroe, the one record with the player_ID 4412680 should be changed to 4260. Final ID for Greg Monroe: 4260.

8. for Ray Spalding, the one record with the player_ID 4415522 should be changed to 3908806. Final ID for Ray Spalding: 3908806.

9. for Wayne Selden, all records with the player_ID 4895499 should be changed to 3059316. Final ID for Wayne Selden: 3059316.
"""
#iterate through hoopR_dupes to get the rows for the players with the appropriate ID of the two
final_IDs = [3191, 4066243, 3906522, 6594, 4236300, 2490589, 4260, 3908806, 3059316]
final_indices = []
i = 0
for idx in range(len(hoopR_dupes.index)):
    if hoopR_dupes.iloc[i, 0] in final_IDs:
        final_indices.append(i)
    i += 1

#join hoopR and nba_api IDs on athlete names and concatenate it to match_IDs
name_dupes = pd.DataFrame(columns=hoopR_dupes.columns)
for idx in final_indices:
    next_row = pd.DataFrame(hoopR_dupes.iloc[idx, ]).T
    name_dupes = pd.concat([name_dupes, next_row], ignore_index=True)
name_dupes = name_dupes.join(nba_api_dupes.set_index('full_name'), on='athlete_display_name')
name_dupes.rename(columns={'athlete_id':'hoopR_ID', 'athlete_display_name':'athlete', 'id':'nba_api_ID'}, inplace=True)

print(match_IDs.shape) #1165 rows
match_IDs = pd.concat([match_IDs, name_dupes], ignore_index=True)
print(match_IDs.shape) #1174 rows
match_IDs.tail() #to see the right rows got concatenated to the end

(1165, 3)
(1174, 3)

     hoopR_ID         athlete  nba_api_ID
1169  3059316    Wayne Selden     1627782
1170  3906522  Henry Ellenson     1627740
1171  3908806    Ray Spalding     1629034
1172  4066243     Daryl Macon     1629133
1173  4236300  Mitchell Creek     1628249

In [66]:
#next step match and concatenate the misspelled athletes by name
"""
As mentioned above about analysis of exclusive athlete names between the two DataFrames in excel (file espn_uniques.xlsx),
25 of the mismatched records are differences in name spelling but refer to the same athlete. 
"""
nba_api_spelling = ['Alexandre Sarr', 'Billy Garrett', 'Boban Marjanović', 'Bogdan Bogdanović',
                    'Bojan Bogdanović', 'Cam Reynolds', 'Carlton Carrington', 'Danté Exum',
                    'Dario Šarić', 'Dennis Schröder', 'Jonas Valančiūnas', 'Jusuf Nurkić',
                    'Karlo Matković', 'Kristaps Porziņģis', 'Luka Dončić', 'Monté Morris', 'Nene',
                    'Nikola Jokić', 'Nikola Jović', 'Nikola Vučević', 'Ruben Nembhard Jr.',
                    'Tidjane Salaün', 'Vasilije Micić', 'Vlatko Čančar', 'Vít Krejčí']
hoopR_spelling = ['Alex Sarr', 'Billy Garrett Jr.', 'Boban Marjanovic', 'Bogdan Bogdanovic',
                  'Bojan Bogdanovic', 'Cameron Reynolds', 'Bub Carrington', 'Dante Exum',
                  'Dario Saric', 'Dennis Schroder', 'Jonas Valanciunas', 'Jusuf Nurkic',
                  'Karlo Matkovic', 'Kristaps Porzingis', 'Luka Doncic', 'Monte Morris',
                  'Nene ', 'Nikola Jokic', 'Nikola Jovic', 'Nikola Vucevic', 'RJ Nembhard Jr.',
                  'Tidjane Salaun', 'Vasilije Micic', 'Vlatko Cancar', 'Vit Krejci']

In [68]:
hoopR_spelling_athletes = hrnd_u.loc[hrnd_u['eName'].isin(hoopR_spelling)]
hoopR_spelling_athletes.drop('eIndex', axis=1, inplace=True)
hoopR_spelling_athletes.reset_index(drop=True, inplace=True)
hoopR_spelling_athletes

C:\Users\oscar\AppData\Local\Temp\ipykernel_26884\2893310437.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hoopR_spelling_athletes.drop('eIndex', axis=1, inplace=True)

        eID               eName
0   5160992           Alex Sarr
1   3059356   Billy Garrett Jr.
2      4376    Boban Marjanovic
3   3037789   Bogdan Bogdanovic
4      3593    Bojan Bogdanovic
5   4845374      Bub Carrington
6   3057240    Cameron Reynolds
7   3102528          Dante Exum
8   3032978         Dario Saric
9   3032979     Dennis Schroder
10     6477   Jonas Valanciunas
11  3102530        Jusuf Nurkic
12  4997538      Karlo Matkovic
13  3102531  Kristaps Porzingis
14  3945274         Luka Doncic
15  3059310        Monte Morris
16     1713               Nene
17  3112335        Nikola Jokic
18  4997528        Nikola Jovic
19     6478      Nikola Vucevic
20  4277916     RJ Nembhard Jr.
21  5211176      Tidjane Salaun
22  3102532      Vasilije Micic
23  4578893          Vit Krejci
24  4230557       Vlatko Cancar

In [70]:
nba_api_spelling_athletes = nand_u.loc[nand_u['nName'].isin(nba_api_spelling)]
nba_api_spelling_athletes.drop('nIndex', axis=1, inplace=True)
nba_api_spelling_athletes.reset_index(drop=True, inplace=True)
nba_api_spelling_athletes

        nID               nName
0   1642259      Alexandre Sarr
1   1628656       Billy Garrett
2   1626246    Boban Marjanović
3    203992   Bogdan Bogdanović
4    202711    Bojan Bogdanović
5   1629244        Cam Reynolds
6   1642267  Carlton Carrington
7    203957          Danté Exum
8    203967         Dario Šarić
9    203471     Dennis Schröder
10   202685   Jonas Valančiūnas
11   203994        Jusuf Nurkić
12  1631255      Karlo Matković
13   204001  Kristaps Porziņģis
14  1629029         Luka Dončić
15  1628420        Monté Morris
16     2403                Nene
17   203999        Nikola Jokić
18  1631107        Nikola Jović
19   202696      Nikola Vučević
20  1630612  Ruben Nembhard Jr.
21  1642275      Tidjane Salaün
22   203995      Vasilije Micić
23  1628427       Vlatko Čančar
24  1630249          Vít Krejčí

In [72]:
"""
comparing the two DataFrames, the rows match except for Bub/Carlton Carrington switched with Cam/Cameron Reynolds and Vlatko Čančar
switched with Vít Krejčí in the nba_api DataFrame Relative to the hoopR DataFrame. I switched their indices in the list below for
matching the two dataframes and changing the names in the nba_api DataFrame to join with the hoopR DataFrame on athlete name.
"""
ls = [0, 1, 2, 3, 4, 6, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 23]
for i in range(25):
    nba_api_spelling_athletes.iloc[i, 1] = hoopR_spelling_athletes.iloc[ls[i], 1]
nba_api_spelling_athletes.head() #show that the names have be changed

       nID              nName
0  1642259          Alex Sarr
1  1628656  Billy Garrett Jr.
2  1626246   Boban Marjanovic
3   203992  Bogdan Bogdanovic
4   202711   Bojan Bogdanovic

In [74]:
#join the tables on the now matching names and concat to match_ID DataFrame
spelling_issue = hoopR_spelling_athletes.join(nba_api_spelling_athletes.set_index('nName'), on='eName')
spelling_issue.rename(columns={'eID':'hoopR_ID', 'eName':'athlete', 'nID':'nba_api_ID'}, inplace=True)

match_IDs = pd.concat([match_IDs, spelling_issue], ignore_index=True)
match_IDs.tail() #see that the correct rows were concatenated and...
#the index reveals that we have the expected number of rows: 1199

     hoopR_ID          athlete  nba_api_ID
1194  4277916  RJ Nembhard Jr.     1630612
1195  5211176   Tidjane Salaun     1642275
1196  3102532   Vasilije Micic      203995
1197  4578893       Vit Krejci     1630249
1198  4230557    Vlatko Cancar     1628427

In [86]:
path = 'C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\nba_api_hoopR_IDs.csv'
match_IDs.to_csv(path)