In [3]:
import pandas as pd
path = 'C:\\Users\\oscar\\big_ahh_files\\nba_transactions_2016_2025(1).csv'
df = pd.read_csv(path)
df.shape

(27193, 5)

In [5]:
df.head()

,Date,Team,Acquired,Relinquished,Notes
0,2016-01-01,76ers,NaN,• Hollis Thompson,corneal abrasion in right eye (DTD)
1,2016-01-01,Hornets,NaN,• Al Jefferson,placed on IL recovering from surgery on right ...
2,2016-01-01,Knicks,NaN,• Cleanthony Early,placed on IL with knee injury (from gunshot wo...
3,2016-01-01,Lakers,NaN,• Kobe Bryant,placed on IL with sore right shoulder
4,2016-01-01,Lakers,• Metta World Peace / Ron Artest,NaN,activated from IL

In [7]:
df.tail()

,Date,Team,Acquired,Relinquished,Notes
27188,2025-10-24,Pistons,NaN,• Caris LeVert,placed on IL with hamstring injury
27189,2025-10-24,Raptors,• Ja'Kobe Walter,NaN,returned to lineup
27190,2025-10-24,Rockets,• Isaiah Crawford,NaN,returned to lineup
27191,2025-10-24,Rockets,• Jae'Sean Tate,NaN,returned to lineup
27192,2025-10-24,Warriors,• Moses Moody,NaN,activated from IL

In [9]:
r = df['Relinquished']
a = df['Acquired']
non_null = []
for name in r:
    if type(name) == str and name not in non_null:
        non_null.append(name)
for name in a:
    if type(name) == str and name not in non_null:
        non_null.append(name)

In [11]:
no_dot = [0] * len(non_null)
i = 0
for name in non_null:
    no_dot[i] = non_null[i][2:]
    i += 1

In [13]:
len(no_dot) #list of all names of athletes that were removed or placed on the injury list in the period

1249

In [15]:
#next match the names to the name in the IDs table
path = 'C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\nba_api_hoopR_IDs.csv'
id_table = pd.read_csv(path)
id_table.head()

   Unnamed: 0  hoopR_ID         athlete  nba_api_ID
0           0       136    Vince Carter        1713
1           1       165  Jamal Crawford        2037
2           2       272   Manu Ginobili        1938
3           3       609   Dirk Nowitzki        1717
4           4       841     Jason Terry        1891

In [17]:
rel_athletes = id_table['athlete']

match_names = [name for name in rel_athletes if name in no_dot]
unique_id = [name for name in rel_athletes if name not in no_dot]
unique_pst = [name for name in no_dot if name not in rel_athletes.values]

print('Number of athlete name matches: ', len(match_names))
print('Unique athlete names in ID table: ', len(unique_id))
print('Unique athlete names in pro sports transactions table: ', len(unique_pst))

Number of athlete name matches:  984
Unique athlete names in ID table:  215
Unique athlete names in pro sports transactions table:  265

In [19]:
for i in range(len(unique_pst) - len(unique_id)): #make the length of the two lists equal to create DataFrame
    unique_id.append('z')
    
unique_id.sort()
unique_pst.sort()
uniques = pd.DataFrame({'id':unique_id, 'pst':unique_pst})
path = 'C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\Excel Analysis\\pst_id_names(1).xlsx'
#uniques.to_excel(path, index=False)

In [21]:
#cross reference against hoopR database and basketball reference to sort players in excel
path = 'C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\Excel Analysis\\pst_id_names(out).xlsx'
mismatch_matched = pd.read_excel(path)
mismatch_matched.head()

               id                                   pst
0      Mike Scott                    (James) Mike Scott
1     Tony Parker                 (William) Tony Parker
2      AJ Johnson                          A.J. Johnson
3  Sasha Vezenkov  Aleksandar Vezenkov / Sasha Vezenkov
4  Brandon Boston  Brandon Boston Jr. / B.J. Boston Jr.

In [23]:
rows, cols = mismatch_matched.shape
print('Athlete matched from unique names of each dataset: ', rows)

#these athletes were sorted out because they played in earlier seasons, later seasons, or played fewer than 10 games in the relevant period
unique_pst = [name for name in unique_pst if name != 'z'] #delete the 'z' items in the list from earlier
print('Athletes that can be removed from the pro sports transactions dataset: ', len(unique_pst) - rows)

#these athletes just didn't get injured in the time period
unique_id = [name for name in unique_id if name != 'z'] #delete the 'z' items in the list from earlier
print('Athletes in the hoopR dataset but not in the pro sports transactions dataset: ', len(unique_id) - rows) #they just didn't get injured

Athlete matched from unique names of each dataset:  83
Athletes that can be removed from the pro sports transactions dataset:  182
Athletes in the hoopR dataset but not in the pro sports transactions dataset:  132

In [25]:
#change the names in the pro sports transactions dataset to match the names in the hoopR datas

#first remove those dots from the string names for the athletes for matching to mismatch_matched information
a = []
for name in df['Acquired']:
    if type(name) == str:
        a.append(name[2:])
    else:
        a.append(name)

r = []
for name in df['Relinquished']:
    if type(name) == str:
        r.append(name[2:])
    else:
        r.append(name)

df['Acquired'] = a
df['Relinquished'] = r
df.head()

,Date,Team,Acquired,Relinquished,Notes
0,2016-01-01,76ers,NaN,Hollis Thompson,corneal abrasion in right eye (DTD)
1,2016-01-01,Hornets,NaN,Al Jefferson,placed on IL recovering from surgery on right ...
2,2016-01-01,Knicks,NaN,Cleanthony Early,placed on IL with knee injury (from gunshot wo...
3,2016-01-01,Lakers,NaN,Kobe Bryant,placed on IL with sore right shoulder
4,2016-01-01,Lakers,Metta World Peace / Ron Artest,NaN,activated from IL

In [27]:
#investigate the rows containing weird names
df[df['Acquired'] == 'fractured rib (out indefinitely)'].head()

Empty DataFrame
Columns: [Date, Team, Acquired, Relinquished, Notes]
Index: []

In [29]:
df[df['Acquired'] == 'illness (DTD)'].head() #from my analysis this is just a duplicate record for Terry Rozier's return one day later.

             Date  Team       Acquired Relinquished               Notes
26770  2025-04-04  Heat  illness (DTD)          NaN  returned to lineup

In [31]:
df.drop(index=26770, inplace=True)

In [33]:
df[df['Acquired'] == 'sore lower back (DTD)'].head() #this is a mistake, the name should be Alperen Senguin.

,Date,Team,Acquired,Relinquished,Notes
26160,2025-03-04,Rockets,sore lower back (DTD),NaN,returned to lineup

In [35]:
df.loc[26160, 'Acquired'] = 'Alperen Sengun'

In [37]:
df[df['Acquired'] == 'torn ACL in left knee (out for season)'].head()

Empty DataFrame
Columns: [Date, Team, Acquired, Relinquished, Notes]
Index: []

In [39]:
df[df['Relinquished'] == 'fractured rib (out indefinitely)'].head() #this is clearly anthony davis

,Date,Team,Acquired,Relinquished,Notes
25549,2025-01-25,Mavericks,NaN,fractured rib (out indefinitely),placed on IL with fractured rib

In [41]:
df.loc[25549, 'Relinquished'] = 'Anthony Davis'

In [43]:
df[df['Relinquished'] == 'illness (DTD)'].head()

Empty DataFrame
Columns: [Date, Team, Acquired, Relinquished, Notes]
Index: []

In [45]:
df[df['Relinquished'] == 'sore lower back (DTD)'].head()

Empty DataFrame
Columns: [Date, Team, Acquired, Relinquished, Notes]
Index: []

In [47]:
df[df['Relinquished'] == 'torn ACL in left knee (out for season)'].head() #just a duplicate of Kyrie Irving's knee injury

,Date,Team,Acquired,Relinquished,Notes
26155,2025-03-04,Mavericks,NaN,torn ACL in left knee (out for season),placed on IL with torn ACL in left knee (out f...

In [49]:
df.drop(index=26155, inplace=True)

In [51]:
#next remove the records of players that are not relevant

#names I want to keep from pro sports transactions: the matching names across both tables and the names in mismatched_match
names_to_keep = match_names
print('names in match_names: ', len(match_names))
for name in list(mismatch_matched['pst']):
    names_to_keep.append(name)

#go through row indices of the pro sports transactions data and if the name in the Acquired or Relinquished column is not in the names I want
#to keep, drop that row
ls = [name for name in no_dot if name not in names_to_keep]
df = df[~df['Acquired'].isin(ls)]
df = df[~df['Relinquished'].isin(ls)]

print('names in names_to_keep: ', len(names_to_keep)) #will be 804 + 69 total athletes
print(df.shape)

names in match_names:  984
names in names_to_keep:  1067
(25980, 5)

In [53]:
#next, change the names in the pro sports transactions data to names that match the IDs table

#define function that returns the corresponding ID table name of a pro sports transactions dataset name
def get_id_from_pst(name):
    target_index = mismatch_matched.index[mismatch_matched['pst'] == name]
    idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
    return mismatch_matched.loc[target_index, 'id'].loc[idx]
    
#iterates through all the mismatched names in pro sports transactions and changes all records containing each name
for old_name in mismatch_matched['pst']:
    new_name = get_id_from_pst(old_name)
    locations = df[df['Acquired'] == old_name].index
    df.loc[locations, 'Acquired'] = new_name
    locations = df[df['Relinquished'] == old_name].index
    df.loc[locations, 'Relinquished'] = new_name

C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)
C:\Users\oscar\AppData\Local\Temp\ipykernel_2756\1975615436.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  idx = int(mismatch_matched.index[mismatch_matched['pst'] == name].values)

In [55]:
ls = [name for name in df['Acquired'].unique()]
for name in df['Relinquished'].unique():
    if name not in ls:
        ls.append(name)
len(ls)

1067

In [57]:
ls

[nan,
 'Bruno Caboclo',
 'Kyrie Irving',
 'Jeremy Lin',
 'Willie Cauley-Stein',
 'Justin Anderson',
 'Danilo Gallinari',
 'Jusuf Nurkic',
 'Ian Mahinmi',
 'Jon Leuer',
 'Stephen Curry',
 'Harrison Barnes',
 'Justise Winslow',
 'Tarik Black',
 'Damian Lillard',
 'Delon Wright',
 'Norman Powell',
 'Kevon Looney',
 'Derrick Rose',
 'Tim Hardaway Jr.',
 'Devin Harris',
 'Luis Montero',
 'RJ Hunter',
 'Hassan Whiteside',
 'Salah Mejri',
 'George Hill',
 'Tyreke Evans',
 'Kevin Durant',
 'Nene ',
 'Justin Holiday',
 'Rudy Gobert',
 'Rajon Rondo',
 "D'Angelo Russell",
 'CJ McCollum',
 'Dirk Nowitzki',
 'Zaza Pachulia',
 'Tony Parker',
 'LaMarcus Aldridge',
 'James Ennis III',
 'Miles Plumlee',
 'Tyler Ennis',
 'Avery Bradley',
 'Nicolas Batum',
 'Rodney Hood',
 'Emmanuel Mudiay',
 'Dwight Howard',
 'Joakim Noah',
 'Tyler Johnson',
 'Courtney Lee',
 'Marcus Morris Sr.',
 'Joe Harris',
 'Thabo Sefolosha',
 'Omri Casspi',
 'John Jenkins',
 'Jameer Nelson',
 'Anthony Davis',
 'Bradley Beal',
 'Cristiano Felicio',
 'Elfrid Payton',
 'Jerryd Bayless',
 'Pau Gasol',
 'Chandler Parsons',
 'Wesley Matthews',
 'Brandon Knight',
 'Marcin Gortat',
 'Dwyane Wade',
 'Jerami Grant',
 'DeAndre Jordan',
 'Mike Conley',
 'Trevor Booker',
 'Carmelo Anthony',
 'Victor Oladipo',
 'Patrick Beverley',
 'Alex Len',
 'Jeremy Lamb',
 'Raymond Felton',
 'Mirza Teletovic',
 'Montrezl Harrell',
 'Nik Stauskas',
 'Terry Rozier',
 'James Young',
 'Tony Allen',
 'Luol Deng',
 'Derrick Favors',
 'Rudy Gay',
 'Kenneth Faried',
 'Dante Cunningham',
 'Tyus Jones',
 'Otto Porter Jr.',
 'Jarell Martin',
 'Lance Thomas',
 'Larry Nance Jr.',
 'Jeremy Evans',
 'Markieff Morris',
 'Steven Adams',
 "E'Twaun Moore",
 'Goran Dragic',
 'Josh McRoberts',
 'Michael Kidd-Gilchrist',
 'Kristaps Porzingis',
 'Lou Williams',
 'Josh Huestis',
 'Jahlil Okafor',
 'JaKarr Sampson',
 'Joffrey Lauvergne',
 'Donatas Motiejunas',
 'Andre Iguodala',
 'Marco Belinelli',
 'Ersan Ilyasova',
 'Cameron Payne',
 'Pat Connaughton',
 'Adreian Payne',
 'Cody Zeller',
 'Ben McLemore',
 'DeMarcus Cousins',
 'Jose Calderon',
 'Clint Capela',
 'Sam Dekker',
 'Jimmy Butler',
 'Kemba Walker',
 'Thanasis Antetokounmpo',
 'Dewayne Dedmon',
 'Chris McCullough',
 'Ish Smith',
 'Richaun Holmes',
 'Allen Crabbe',
 'Kevin Love',
 'Noah Vonleh',
 'Kyle Anderson',
 'Matthew Dellavedova',
 'Trey Burke',
 'Nerlens Noel',
 'Jordan Mickey',
 'Brandan Wright',
 'Al Jefferson',
 'Anthony Brown',
 'Jason Smith',
 'Darrell Arthur',
 'Kentavious Caldwell-Pope',
 'Reggie Bullock Jr.',
 'Reggie Jackson',
 'Tobias Harris',
 'James Johnson',
 'Lance Stephenson',
 'CJ Miles',
 'Andre Roberson',
 'Andrew Bogut',
 'Terrence Jones',
 'Kawhi Leonard',
 'Tyson Chandler',
 'T.J. McConnell',
 'Iman Shumpert',
 'James Michael McAdoo',
 'Eric Gordon',
 'Shabazz Napier',
 'LeBron James',
 'Jarell Eddie',
 'Udonis Haslem',
 'Arron Afflalo',
 'Austin Rivers',
 'Kyle Lowry',
 'JaVale McGee',
 'Evan Fournier',
 'Nikola Mirotic',
 'Taj Gibson',
 'Omer Asik',
 'Manu Ginobili',
 'Jordan Clarkson',
 'Kosta Koufos',
 'Luke Babbitt',
 'Timofey Mozgov',
 'Anthony Tolliver',
 'Stanley Johnson',
 'Nemanja Bjelica',
 'Mike Scott',
 'Luc Mbah a Moute',
 'Joe Young',
 'John Henson',
 'Brandon Jennings',
 'Wayne Ellington',
 'Kelly Olynyk',
 'Spencer Dinwiddie',
 'DeMar DeRozan',
 'Jonathon Simmons',
 'Jonas Valanciunas',
 'Vince Carter',
 'Zach Randolph',
 'Kent Bazemore',
 'Gordon Hayward',
 'Willie Reed',
 'Serge Ibaka',
 'Eric Moreland',
 'Jonas Jerebko',
 'Brook Lopez',
 'Rondae Hollis-Jefferson',
 'Robert Covington',
 'Jeff Green',
 'Boban Marjanovic',
 'Marvin Williams',
 'Patrick Patterson',
 'Kyle Singler',
 'Blake Griffin',
 'Jrue Holiday',
 'Nick Young',
 'Terrence Ross',
 'Jae Crowder',
 'Nikola Vucevic',
 'David West',
 'JJ Redick',
 'Darren Collison',
 'DeMarre Carroll',
 'Ian Clark',
 'Evan Turner',
 'Alec Burks',
 'Lorenzo Brown',
 'Khris Middleton',
 'Wesley Johnson',
 'Aaron Harrison',
 'J.J. Barea',
 'Aaron Gordon',
 'Jodie Meeks',
 'Isaiah Thomas',
 'JR Smith',
 'John Holland',
 'Darrun Hilliard',
 'Anderson Varejao',
 'Briante Weber',
 'Lucas Nogueira',
 'Jordan McRae',
 'Frank Kaminsky',
 'Marc Gasol',
 'Aron Baynes',
 'Chris Paul',
 'Georges Niang',
 'Damian Jones',
 'Tony Snell',
 'Kay Felder',
 'Dejounte Murray',
 'Skal Labissiere',
 'Aaron Brooks',
 'Jerian Grant',
 'Marcus Smart',
 'Ron Baker',
 'Ivica Zubac',
 'Devin Booker',
 'Chinanu Onuaku',
 'Doug McDermott',
 'Josh Richardson',
 'Willy Hernangomez',
 'Davis Bertans',
 'Georgios Papagiannis',
 'Gary Harris',
 'Danuel House Jr.',
 'Jason Terry',
 'Christian Wood',
 'Patrick McCaw',
 'John Wall',
 'Tim Quarterman',
 'Danny Green',
 'Bryn Forbes',
 'Wilson Chandler',
 'Ricky Rubio',
 'Isaiah Whitehead',
 'DeAndre Liggins',
 'Paul George',
 'Henry Ellenson',
 'Zach LaVine',
 'Andre Drummond',
 'Al Horford',
 'Troy Daniels',
 'Derrick Jones Jr.',
 'Shabazz Muhammad',
 'Will Barton',
 'Marshall Plumlee',
 'Treveon Graham',
 'Myles Turner',
 'Timothe Luwawu-Cabarrot',
 'Rashad Vaughn',
 'Kyle Korver',
 'Joel Embiid',
 'Draymond Green',
 'Julius Randle',
 'Bobby Brown',
 'Juancho Hernangomez',
 'Jared Dudley',
 'Paul Zipser',
 "DeAndre' Bembry",
 'Derrick Williams',
 'Al-Farouq Aminu',
 'Paul Millsap',
 'Caris LeVert',
 'Demetrius Jackson',
 'Yogi Ferrell',
 'Nikola Jokic',
 'Malik Beasley',
 'Seth Curry',
 'Maurice Harkless',
 'Shaun Livingston',
 "Kyle O'Quinn",
 'Malachi Richardson',
 'Tim Frazier',
 'T.J. Warren',
 'Gerald Green',
 'Kelly Oubre Jr.',
 'Cory Joseph',
 'Michael Beasley',
 'Michael Carter-Williams',
 'Rodney McGruder',
 'Wade Baldwin IV',
 'Dion Waiters',
 'Troy Williams',
 'Dante Exum',
 'JaMychal Green',
 'Denzel Valentine',
 'Taurean Prince',
 'Cheick Diallo',
 'Giannis Antetokounmpo',
 'Deyonta Davis',
 'Mindaugas Kuzminskas',
 'Klay Thompson',
 'Amir Johnson',
 'Jaylen Brown',
 'Raul Neto',
 'Tomas Satoransky',
 'Nicolas Brussino',
 'Joe Johnson',
 'Patty Mills',
 'Ed Davis',
 'Ryan Anderson',
 'Tyler Zeller',
 'Richard Jefferson',
 'Mike Muscala',
 'D.J. Augustin',
 'Isaiah Canaan',
 'Dragan Bender',
 'Alex Abrines',
 'Kris Dunn',
 'Eric Bledsoe',
 'Brice Johnson',
 'Thaddeus Young',
 'Enes Freedom',
 'Axel Toupane',
 'Quincy Acy',
 'Garrett Temple',
 'Jarrett Jack',
 'Joel Bolomboy',
 'Malcolm Brogdon',
 'Jarrod Uthoff',
 'Alan Williams',
 'Shelvin Mack',
 'Sean Kilpatrick',
 'Bojan Bogdanovic',
 'Brandon Ingram',
 'Isaiah Taylor',
 'Andrew Harrison',
 'P.J. Tucker',
 'James Harden',
 'Malcolm Delaney',
 'Chasson Randle',
 'Jabari Parker',
 'Dennis Schroder',
 "Johnny O'Bryant III",
 'Trevor Ariza',
 'Tristan Thompson',
 'Pascal Siakam',
 'Jeff Withey',
 'Jabari Bird',
 'Zach Collins',
 'Guerschon Yabusele',
 'Josh Hart',
 'Wes Iwundu',
 'Alex Poythress',
 'Ike Anigbogu',
 'Quinn Cook',
 'Ante Zizic',
 'Kobi Simmons',
 'Okaro White',
 'Nate Wolters',
 'Khem Birch',
 'Mangok Mathiang',
 'Dennis Smith Jr.',
 'Bogdan Bogdanovic',
 'Jawun Evans',
 'Tony Bradley',
 'Antonio Blakeney',
 'Frank Ntilikina',
 'Dwight Buycks',
 'Matt Costello',
 'Furkan Korkmaz',
 'Jonathan Isaac',
 'Jordan Bell',
 'Ivan Rabb',
 'Devin Robinson',
 'Luke Kennard',
 'Wayne Selden',
 'Thomas Bryant',
 'Vander Blue',
 'Derrick Walton Jr.',
 'Dorian Finney-Smith',
 'T.J. Leaf',
 'Alfonzo McKinnie',
 'C.J. Williams',
 'Domantas Sabonis',
 'Alec Peters',
 'Jarrett Allen',
 'Meyers Leonard',
 'Gary Payton II',
 'Charles Cooke',
 'Jalen Jones',
 'Daniel Hamilton',
 'Cole Aldrich',
 'Greg Monroe',
 'Jack Cooley',
 'Gorgui Dieng',
 'Tyler Lydon',
 'Sterling Brown',
 'Buddy Hield',
 'Josh Magette',
 'Tyler Dorsey',
 'Shane Larkin',
 'Ben Simmons',
 'D.J. Wilson',
 'Torrey Craig',
 'Julyan Stone',
 'David Nwaba',
 'Mario Chalmers',
 'Jeff Teague',
 'Caleb Swanigan',
 'Kyle Kuzma',
 'Derrick White',
 'Bobby Portis',
 'Dakari Johnson',
 'Johnathan Motley',
 'Dario Saric',
 'Kadeem Allen',
 'Justin Jackson',
 'Milos Teodosic',
 'Monte Morris',
 'Zhou Qi',
 'Jamel Artis',
 'John Collins',
 'Lauri Markkanen',
 "De'Aaron Fox",
 'Alex Caruso',
 'Malcolm Miller',
 'Donovan Mitchell',
 'Milton Doyle',
 'Damyean Dotson',
 'Brandon Paul',
 'Semi Ojeleye',
 'Lonzo Ball',
 'Davon Reed',
 'Josh Jackson',
 'Abdel Nader',
 'Myke Henry',
 'Jamal Murray',
 'Ryan Arcidiacono',
 'Fred VanVleet',
 'Ben Moore',
 'Jamal Crawford',
 'Channing Frye',
 'Marquese Chriss',
 'James Webb III',
 'Nigel Hayes',
 'Markel Brown',
 'Cedi Osman',
 'Xavier Munford',
 'Erik McCree',
 'Reggie Hearn',
 'Isaiah Hicks',
 'Luke Kornet',
 'PJ Dozier',
 'Marcus Georges-Hunt',
 'Russell Westbrook',
 'Andrew White III',
 'Tyler Ulis',
 'Frank Mason III',
 'Mason Plumlee',
 'Glenn Robinson III',
 'Justin Patton',
 'Amile Jefferson',
 'Daniel Theis',
 'Dwayne Bacon',
 'Emeka Okafor',
 'Robin Lopez',
 'Terrance Ferguson',
 'Tyler Cavanaugh',
 'Chris Boucher',
 'OG Anunoby',
 'Solomon Hill',
 'Marcus Paige',
 'Markelle Fultz',
 'Tyrone Wallace',
 'Dwight Powell',
 'Bam Adebayo',
 'Travis Wear',
 'Thon Maker',
 'Antonius Cleveland',
 'MarShon Brooks',
 'Jayson Tatum',
 'Edmond Sumner',
 'David Stockton',
 'Jake Layman',
 'Kendrick Perkins',
 'Ramon Sessions',
 'Alize Johnson',
 'Robert Williams III',
 "Devonte' Graham",
 'Melvin Frazier Jr.',
 'Omari Spellman',
 "De'Anthony Melton",
 'Damion Lee',
 'Moritz Wagner',
 'Yuta Watanabe',
 'Jaylen Adams',
 'Andrew Wiggins',
 'Rodions Kurucs',
 'Gary Trent Jr.',
 'Darius Miller',
 'Kevin Knox II',
 'Bruce Brown',
 'Jacob Evans',
 'Shake Milton',
 'Jakob Poeltl',
 'Dzanan Musa',
 'Mario Hezonja',
 'Jevon Carter',
 'Chandler Hutchison',
 'Donte DiVincenzo',
 'Hamidou Diallo',
 'Bismack Biyombo',
 'Frank Jackson',
 'Luka Doncic',
 'Maxi Kleber',
 'Jonah Bolden',
 'Marvin Bagley III',
 'Isaiah Hartenstein',
 'Anfernee Simons',
 'Ryan Broekhoff',
 'Jerome Robinson',
 'Dillon Brooks',
 'Harry Giles III',
 'Allonzo Trier',
 'Lonnie Walker IV',
 'Keita Bates-Diop',
 'Kevin Huerter',
 'Grayson Allen',
 'Trey Lyles',
 'Mitchell Robinson',
 'Mo Bamba',
 'Khyri Thomas',
 'Kostas Antetokounmpo',
 'Jarred Vanderbilt',
 'Deandre Ayton',
 'Jaren Jackson Jr.',
 'Troy Brown Jr.',
 'Karl-Anthony Towns',
 'Brad Wanamaker',
 'Svi Mykhailiuk',
 'Ekpe Udoh',
 'Zhaire Smith',
 'Landry Shamet',
 'Shaquille Harrison',
 'Tacko Fall',
 'Jordan Bone',
 'Cameron Johnson',
 'Romeo Langford',
 'Amir Coffey',
 'Nic Claxton',
 'Trae Young',
 'Brandon Clarke',
 'Eric Paschall',
 'Bol Bol',
 'Tyler Herro',
 'Goga Bitadze',
 'Josh Okogie',
 'Naz Reid',
 'Max Strus',
 'Sekou Doumbouya',
 'Cam Reddish',
 'RJ Barrett',
 'Alen Smailagic',
 'Nigel Williams-Goss',
 'Dewan Hernandez',
 'Chimezie Metu',
 'Ty Jerome',
 'Juwan Morgan',
 'Kenrich Williams',
 "De'Andre Hunter",
 'Vlatko Cancar',
 'Ja Morant',
 'KZ Okpala',
 'Malik Monk',
 'Daniel Gafford',
 'Nassir Little',
 'Jarrett Culver',
 'Jalen Lecque',
 'P.J. Washington',
 'Adam Mokoka',
 'Jordan Poole',
 'Terance Mann',
 'Isaiah Roby',
 'Matt Thomas',
 'Matisse Thybulle',
 'Michael Frazier II',
 'Vincent Poirier',
 'Naz Mitrou-Long',
 'Zion Williamson',
 'Dean Wade',
 'Anzejs Pasecniks',
 'Michael Porter Jr.',
 'Kevin Porter Jr.',
 'Gabe Vincent',
 'Javonte Green',
 'Kendrick Nunn',
 'Garrison Mathews',
 'Jared Harper',
 'Rui Hachimura',
 'Bruno Fernando',
 'Marko Guduric',
 'Cody Martin',
 'Deonte Burton',
 'Jaylen Nowell',
 'Norvel Pelle',
 'Kyle Alexander',
 'Wendell Carter Jr.',
 'Ky Bowman',
 'Shai Gilgeous-Alexander',
 'Darius Bazley',
 'Isaac Bonga',
 'Oshae Brissett',
 "Royce O'Neale",
 'Elie Okobo',
 'Chris Chiozza',
 'Donta Hall',
 'Luguentz Dort',
 'Vic Law',
 'Tremont Waters',
 'Chris Silva',
 'Jordan McLaughlin',
 'Grant Riller',
 'Devon Dotson',
 'Immanuel Quickley',
 'Xavier Tillman',
 'KJ Martin',
 'Wenyen Gabriel',
 'Isaac Okoro',
 'Trent Forrest',
 'Tyrese Haliburton',
 'Jalen Smith',
 'Nick Richards',
 'Sam Merrill',
 'Reggie Perry',
 'Sindarius Thornwell',
 'Mason Jones',
 'Aleksej Pokusevski',
 'Joe Ingles',
 'John Konchar',
 "Jahmi'us Ramsey",
 'Obi Toppin',
 'Grant Williams',
 'Onyeka Okongwu',
 'Killian Tillie',
 'Brian Bowen II',
 'Jalen Brunson',
 'Brodric Thomas',
 'Collin Sexton',
 'Dylan Windler',
 'Luka Samanic',
 'Patrick Williams',
 'Darius Garland',
 'Chris Clemons',
 'Carsen Edwards',
 'CJ Elleby',
 'Aaron Nesmith',
 'Keljin Blevins',
 'Lamar Stevens',
 'Markus Howard',
 'Drew Eubanks',
 'Quinndary Weatherspoon',
 'Nate Darling',
 'Josh Hall',
 'Jay Scrubb',
 'Deni Avdija',
 'Chuma Okeke',
 'Jontay Porter',
 'Payton Pritchard',
 'Naji Marshall',
 'Theo Maledon',
 'Facundo Campazzo',
 'DaQuan Jeffries',
 'Sean McDermott',
 'Jalen McDaniels',
 'Anthony Gill',
 'Elijah Hughes',
 'Tyrell Terry',
 'James Wiseman',
 'Caleb Martin',
 'Keldon Johnson',
 'Mamadi Diakite',
 'Devin Vassell',
 'Jordan Nwora',
 'Zeke Nnaji',
 'Mfiondu Kabengele',
 'Jaden McDaniels',
 'Robert Woodard II',
 'Malachi Flynn',
 'R.J. Hampton',
 'Brandon Goodwin',
 'Nicolo Melli',
 'Jaxson Hayes',
 'Ignas Brazdeikis',
 'Gary Clark',
 'Coby White',
 'Killian Hayes',
 'Tyrese Maxey',
 'Cole Anthony',
 'Kira Lewis Jr.',
 'Armoni Brooks',
 'Juan Toscano-Anderson',
 'Paul Watson',
 'Myles Powell',
 'Paul Reed',
 'Gabriel Deck',
 'LaMelo Ball',
 'Devin Cannady',
 'Udoka Azubuike',
 "Jae'Sean Tate",
 'Talen Horton-Tucker',
 'Miles Bridges',
 'Omer Yurtseven',
 'Ty-Shon Alexander',
 "Day'Ron Sharpe",
 'Louis King',
 'Malik Fitts',
 'Eugene Omoruyi',
 'Miye Oni',
 'Cade Cunningham',
 'Jonathan Kuminga',
 'Vernon Carey Jr.',
 'Isaiah Livers',
 'Keon Johnson',
 'Kelan Martin',
 'Brandon Boston',
 'Scottie Barnes',
 'Jaden Springer',
 'Devontae Cacok',
 'Isaiah Todd',
 'RJ Nembhard Jr.',
 'Ziaire Williams',
 'Herbert Jones',
 'Cassius Winston',
 'Yves Pons',
 'Alperen Sengun',
 'Marko Simonovic',
 'Terence Davis',
 'Isaiah Joe',
 'Trendon Watford',
 'Isaiah Jackson',
 'Greg Brown III',
 'Kessler Edwards',
 'Marcus Garrett',
 'Jalen Suggs',
 'Chris Duarte',
 'Saben Lee',
 'Precious Achiuwa',
 'Sam Hauser',
 'McKinley Wright IV',
 'Jock Landale',
 'Sandro Mamukelashvili',
 'Austin Reaves',
 'Evan Mobley',
 'Bones Hyland',
 'JT Thor',
 'Neemias Queta',
 'David Duke Jr.',
 'Aaron Holiday',
 'Jericho Sims',
 'Kai Jones',
 'Scottie Lewis',
 'Josh Giddey',
 'Usman Garuba',
 'Dalano Banton',
 'Jared Butler',
 'Jose Alvarado',
 'Ayo Dosunmu',
 'Quentin Grimes',
 'Jalen Green',
 'Josh Green',
 'BJ Johnson',
 'Miles McBride',
 'Davion Mitchell',
 'Cam Thomas',
 'Moses Moody',
 'Santi Aldama',
 'Justin Champagnie',
 'Ish Wainright',
 'Anthony Edwards',
 'Moses Wright',
 'Matt Mooney',
 'Sharife Cooper',
 'Malcolm Hill',
 'Zylan Cheatham',
 'Mychal Mulder',
 'Jaylen Hoard',
 'Tre Mann',
 'Duncan Robinson',
 'David Johnson',
 'Jeremiah Robinson-Earl',
 'Brandon Williams',
 'Isaiah Stewart',
 'Olivier Sarr',
 'Scotty Hopson',
 'Jalen Johnson',
 'Desmond Bane',
 'Xavier Moon',
 'Leandro Bolmaro',
 'Langston Galloway',
 'Tyler Cook',
 'Tre Jones',
 'Luka Garza',
 'Lindell Wigginton',
 'Trey Murphy III',
 'Vit Krejci',
 'Jamorko Pickett',
 'James Bouknight',
 'Terry Taylor',
 'Aaron Wiggins',
 'Joshua Primo',
 'Joe Wieskamp',
 'Didi Louzada',
 'Duane Washington Jr.',
 'Skylar Mays',
 'Franz Wagner',
 'Theo Pinson',
 'Admiral Schofield',
 'Charles Bassey',
 'Daishen Nix',
 'Jaden Ivey',
 'Jake LaRavia',
 'Walker Kessler',
 'Jeremy Sochan',
 'Corey Kispert',
 'Mark Williams',
 'Jalen Duren',
 'AJ Green',
 'Keegan Murray',
 'Patrick Baldwin Jr.',
 'Cole Swider',
 'Paolo Banchero',
 'Peyton Watson',
 'Saddiq Bey',
 'Andrew Nembhard',
 'Johnny Davis',
 'Chima Moneke',
 'MarJon Beauchamp',
 'Alondes Williams',
 'Vince Williams Jr.',
 'Johnny Juzang',
 'Blake Wesley',
 'Simone Fontecchio',
 'Moussa Diabate',
 'Jabari Smith Jr.',
 'Orlando Robinson',
 'Dyson Daniels',
 'Malaki Branham',
 'Jalen Williams',
 'Bennedict Mathurin',
 'Jack White',
 'Lindy Waters III',
 'Matt Ryan',
 'Kevon Harris',
 'Shaedon Sharpe',
 'Nikola Jovic',
 'Bryce McGowens',
 'Jalen Slawson',
 'Jaden Hardy',
 'Nate Hinton',
 'Jay Huff',
 'Haywood Highsmith',
 'Dariq Whitehead',
 'Jaylin Williams',
 'Jarace Walker',
 'Tari Eason',
 'Jamal Cain',
 'Dereck Lively II',
 'Brandon Miller',
 'Jalen Hood-Schifino',
 'Dalen Terry',
 'Trayce Jackson-Davis',
 'Sasha Vezenkov',
 'Javon Freeman-Liberty',
 'Scoot Henderson',
 'Chris Livingston',
 'AJ Griffin',
 'Bilal Coulibaly',
 'Justin Minaya',
 'Keon Ellis',
 'Hunter Tyson',
 'Victor Wembanyama',
 'Andre Jackson Jr.',
 'Noah Clowney',
 'Gradey Dick',
 'Amen Thompson',
 'Onuralp Bitim',
 'Colby Jones',
 'Josh Minott',
 'TyTy Washington Jr.',
 'Ryan Rollins',
 'Kobe Bufkin',
 'Keyonte George',
 'Henri Drell',
 'Toumani Camara',
 'Seth Lundy',
 'Gui Santos',
 'Jabari Walker',
 'Maxwell Lewis',
 'Ibou Badji',
 'Christian Koloko',
 'Julian Phillips',
 'Kenneth Lofton Jr.',
 'Ousmane Dieng',
 'Jaime Jaquez Jr.',
 'Sidy Cissoko',
 'Julian Strawther',
 'Ochai Agbaji',
 'Brice Sensabaugh',
 'Duop Reath',
 'Cam Whitmore',
 'Max Christie',
 'Braxton Key',
 'Wendell Moore Jr.',
 'Rayan Rupert',
 'Mouhamed Gueye',
 'Moses Brown',
 'Marcus Sasser',
 'Ben Sheppard',
 'Julian Champagnie',
 'Brandin Podziemski',
 'Dru Smith',
 'GG Jackson',
 'Jordan Goodwin',
 'Scotty Pippen Jr.',
 'Amari Bailey',
 'Taylor Hendricks',
 'JD Davison',
 'Colin Castleton',
 'Vasilije Micic',
 'Craig Porter Jr.',
 'Leaky Black',
 'Caleb Houstan',
 'Tristan Vukcevic',
 'Jordan Ford',
 'Olivier-Maxence Prosper',
 "Kel'el Ware",
 'Dominick Barlow',
 'Tristan da Silva',
 "Ja'Kobe Walter",
 'Johnny Furphy',
 'Jaylon Tyson',
 'Jordan Hawkins',
 'Isaiah Collier',
 'Ryan Dunn',
 'Ausar Thompson',
 'Cam Spencer',
 'Liam Robbins',
 'Yves Missi',
 'AJ Johnson',
 'Quincy Olivari',
 'Tyler Kolek',
 'Kris Murray',
 'Adama Sanogo',
 'Isaiah Crawford',
 'Jalen Wilson',
 'D.J. Carton',
 'Adam Flagler',
 'Tyler Smith',
 'Micah Potter',
 'Bronny James',
 'Kyle Filipowski',
 'Rob Dillingham',
 'Alex Sarr',
 'Donovan Clingan',
 'Tidjane Salaun',
 'Zach Edey',
 'Stephon Castle',
 'Adem Bona',
 'Ariel Hukporti',
 'Christian Braun',
 'Kyshawn George',
 'Pelle Larsson',
 'Matas Buzelis',
 'Jamal Shead',
 'Cason Wallace',
 'Kobe Brown',
 'Trevelin Queen',
 'Anthony Black',
 'Collin Gillespie',
 'Oso Ighodaro',
 'Yuki Kawamura',
 ...]

In [59]:
i = 0
for name in ls:
    if type(name) is float:
        nan_index = i
    i += 1
ls.pop(nan_index)
len(ls) # now list only contains the 1066 player names I want

1066

In [61]:
#the indices of the list ls will serve as the ID for the players in the pro sports transactions dataset
def get_index(value, ls):
    i = 0
    for item in ls:
        if item == value:
            return i
        i += 1

In [63]:
#add a player_id column to make it easier to isolate a single player's records
df['player_id'] = None

for index, row in df.iterrows():
    if type(row['Acquired']) == str:
        df.loc[index, 'player_id'] = get_index(row['Acquired'], ls) 
    else:
        df.loc[index, 'player_id'] = get_index(row['Relinquished'], ls)

In [65]:
df.head()

,Date,Team,Acquired,Relinquished,Notes,player_id
1,2016-01-01,Hornets,NaN,Al Jefferson,placed on IL recovering from surgery on right ...,133
5,2016-01-01,Mavericks,NaN,Devin Harris,back spasms (DTD),19
6,2016-01-01,Mavericks,NaN,Justin Anderson,placed on IL,4
12,2016-01-01,Raptors,Bruno Caboclo,NaN,activated from IL,0
15,2016-01-02,Cavaliers,Kyrie Irving,NaN,activated from IL,1

In [67]:
pst_key = pd.DataFrame(columns=['pst_name', 'pst_id'])
for index, row in df.iterrows():
    if type(row['Acquired']) == str:
        if row['Acquired'] in pst_key['pst_name'].values:
            continue
        else:
            new_df = pd.DataFrame({'pst_name':[row['Acquired']], 'pst_id':[row['player_id']]})
            pst_key = pd.concat([pst_key, new_df])
    else:
        if row['Relinquished'] in pst_key['pst_name'].values:
            continue
        else:
            new_df = pd.DataFrame({'pst_name':[row['Relinquished']], 'pst_id':[row['player_id']]})
            pst_key = pd.concat([pst_key, new_df])

pst_key.shape

(1071, 2)

In [69]:
pst_key

           pst_name pst_id
0      Al Jefferson    133
0      Devin Harris     19
0   Justin Anderson      4
0     Bruno Caboclo      0
0      Kyrie Irving      1
..              ...    ...
0      Quinten Post   1029
0      Jaylen Wells   1063
0        Alex Reese   1030
0     Reece Beekman   1064
0   Quenton Jackson   1065

[1071 rows x 2 columns]

In [71]:
len(pst_key['pst_name'].unique())

1067

In [73]:
#find the names that are null values and assign their value to the variable null_value
ls = []
for name in pst_key['pst_name']:
    if name not in ls:
        ls.append(name)
    else:
        null_value = name

In [75]:
#eliminate the rows that contain the null value
pst_key = pst_key[pst_key['pst_name'] != null_value]
len(pst_key['pst_name'].unique())

1067

In [77]:
len(pst_key['pst_id'].unique())

1067

In [79]:
empty = []
for item in pst_key['pst_id'].values:
    if item in empty:
        print(item)
    else:
        empty.append(item)
        null_value = item

None
None
None
None

In [81]:
pst_key[pst_key['pst_id'] == null_value]

          pst_name pst_id
0  Quenton Jackson   1065

In [83]:
empty = []
for item in pst_key['pst_name'].values:
    if item in empty:
        print(item)
    else:
        empty.append(item)

nan
nan
nan
nan

In [85]:
pst_key = pst_key.dropna()
pst_key.shape

(1066, 2)

In [87]:
ls = [name for name in id_table['athlete'] if name not in pst_key['pst_name'].values]
ls[0]

'Nick Collison'

In [89]:
#print the names of the athletes that weren't injured in the relevant period
ls

['Nick Collison',
 'Josh Smith',
 'Damien Wilkins',
 'Marreese Speights',
 'Jordan Crawford',
 'Jimmer Fredette',
 'Jeremy Pargo',
 'Xavier Silas',
 'Marquis Teague',
 'Scott Machado',
 'Andre Ingram',
 'Aaron Jackson',
 'Jonathan Gibson',
 'Kalin Lucas',
 'James Nunnally',
 'Mike James',
 'Kyle Collinsworth',
 'Walt Lemon Jr.',
 'Julian Washburn',
 'Dairis Bertans',
 'Jordan Loyd',
 'Jaron Blossomgame',
 'Rodney Purvis',
 'Gabe York',
 'Josh Gray',
 'Joe Chealey',
 'Devon Hall',
 'George King',
 'Johnathan Williams',
 'Troy Caupain',
 'Amida Brimah',
 'Donte Grantham',
 'Xavier Cooks',
 'Elijah Bryant',
 'Jared Terrell',
 'Yante Maten',
 'Angel Delgado',
 'J.P. Macura',
 'Vincent Edwards',
 'Bonzie Colson',
 'Marial Shayok',
 'Kevin Hervey',
 'Mikal Bridges',
 'Tariq Owens',
 'Thomas Welsh',
 'Brandon Sampson',
 'Jeremiah Martin',
 'Deng Adel',
 'Rayjon Tucker',
 'Justin Wright-Foreman',
 'Jack McVeigh',
 'Josh Reaves',
 'Isaac Humphries',
 'Marcus Derrickson',
 'Marques Bolden',
 'Kyle Guy',
 'Xavier Sneed',
 'Rawle Alkins',
 'Charlie Brown Jr.',
 'Jeff Dowtin Jr.',
 'Taze Moore',
 'A.J. Lawson',
 'Jemerrio Jones',
 'Carlik Jones',
 'Arnoldas Kulboka',
 'William Howard',
 'RaiQuan Gray',
 'Malik Williams',
 'Freddie Gillespie',
 'Jacob Gilyard',
 'Tyler Bey',
 'Jermaine Samuels Jr.',
 'Jordan Schakel',
 'Daeqwon Plowden',
 'Jamaree Bouyea',
 'Buddy Boeheim',
 'Keyontae Johnson',
 'Ashton Hagans',
 'Feron Hunt',
 'Javonte Smart',
 'Darius Days',
 'Mac McClung',
 'Jules Bernard',
 'Tyrese Martin',
 'Ron Harper Jr.',
 'Andrew Funk',
 'Nate Williams',
 'Tolu Smith',
 'Jalen Pickett',
 'Nico Mannion',
 'Matt Hurt',
 'Cassius Stanley',
 'Keion Brooks Jr.',
 'Lester Quinones',
 'Dereon Seabron',
 'Jesse Edwards',
 'RayJ Dennis',
 'Josh Christopher',
 'Isaiah Mobley',
 'Emanuel Miller',
 'Jalen Bridges',
 'Trey Alexander',
 'Harrison Ingram',
 'Donovan Williams',
 "N'Faly Dante",
 'Antonio Reeves',
 'Pat Spencer',
 'Tristen Newton',
 'David Roddy',
 'Baylor Scheierman',
 'Tosan Evbuomwan',
 'Ronald Holland II',
 'KJ Simpson',
 'Terquavion Smith',
 'PJ Hall',
 'Ricky Council IV',
 'Dillon Jones',
 'Jazian Gortman',
 'Alex Fudge',
 'Malevy Leons',
 'Dalton Knecht',
 'Gabriel Lundberg',
 'Luke Travers',
 'Trevor Hudgins',
 'Daniss Jenkins',
 'Riley Minix',
 'Corey Brewer',
 'Ray Spalding',
 'Daryl Macon',
 'Mitchell Creek',
 'Billy Garrett Jr.',
 'Bub Carrington',
 'Cameron Reynolds']

In [91]:
pst_key[pst_key['pst_name'] == 'Stephen Curry']

        pst_name pst_id
0  Stephen Curry      9

In [93]:
pst_name_id = {}
for index, row in pst_key.iterrows():
    pst_name_id[row['pst_name']] = row['pst_id']
print(pst_name_id)

{'Al Jefferson': 133, 'Devin Harris': 19, 'Justin Anderson': 4, 'Bruno Caboclo': 0, 'Kyrie Irving': 1, 'Avery Bradley': 40, 'RJ Hunter': 21, 'Nicolas Batum': 41, 'Jeremy Lin': 2, 'Willie Cauley-Stein': 3, 'Danilo Gallinari': 5, 'Jusuf Nurkic': 6, 'Ian Mahinmi': 7, 'Tyreke Evans': 25, 'Donatas Motiejunas': 104, 'Jon Leuer': 8, 'James Michael McAdoo': 151, 'Stephen Curry': 9, 'Harrison Barnes': 10, 'Justise Winslow': 11, 'Jarrett Jack': 343, 'Tarik Black': 12, 'Luis Montero': 20, 'Damian Lillard': 13, 'Joe Harris': 49, 'Mike Conley': 67, 'Hassan Whiteside': 22, 'Omri Casspi': 51, "D'Angelo Russell": 31, 'Elfrid Payton': 57, 'George Hill': 24, 'DeMarre Carroll': 209, 'Delon Wright': 14, 'Norman Powell': 15, 'Tony Parker': 35, 'Kevin Durant': 26, 'Kevon Looney': 16, 'Jerryd Bayless': 58, 'Derrick Rose': 17, 'Justin Holiday': 28, 'Tim Hardaway Jr.': 18, 'Rajon Rondo': 30, 'CJ McCollum': 32, 'Josh Richardson': 246, 'Dirk Nowitzki': 33, 'Wesley Matthews': 61, 'Zaza Pachulia': 34, 'Salah Mejri': 23, 'LaMarcus Aldridge': 36, 'Tyus Jones': 86, 'Nene ': 27, 'Rodney Hood': 42, 'Rudy Gobert': 29, 'Dwight Howard': 44, 'Miles Plumlee': 38, 'Tyler Ennis': 39, 'Courtney Lee': 47, 'John Jenkins': 52, 'Anthony Davis': 54, 'Jarell Martin': 88, 'James Ennis III': 37, 'Jeff Teague': 425, 'Thabo Sefolosha': 50, 'Tyler Johnson': 46, 'Jameer Nelson': 53, 'Marcus Morris Sr.': 48, 'Emmanuel Mudiay': 43, 'Cristiano Felicio': 56, 'Joakim Noah': 45, 'Quincy Pondexter': 1034, 'Marcin Gortat': 63, 'DeAndre Jordan': 66, 'Alex Len': 72, 'Brandon Knight': 62, 'Goran Dragic': 95, 'Carmelo Anthony': 69, 'Chandler Parsons': 60, 'Draymond Green': 279, 'Bradley Beal': 55, 'Jerami Grant': 65, 'Pau Gasol': 59, 'Jeremy Lamb': 73, 'Dwyane Wade': 64, 'Otto Porter Jr.': 87, 'Nik Stauskas': 77, 'Trevor Booker': 68, 'Larry Nance Jr.': 90, 'Patrick Beverley': 71, 'Victor Oladipo': 70, 'Lance Thomas': 89, 'Eric Gordon': 152, 'Raymond Felton': 74, 'Tony Allen': 80, 'Cody Zeller': 111, 'Rudy Gay': 83, 'Markieff Morris': 92, 'Mirza Teletovic': 75, 'P.J. Tucker': 354, 'Jordan Mickey': 131, 'Luol Deng': 81, 'Jeremy Evans': 91, 'Montrezl Harrell': 76, 'Steven Adams': 93, 'Kenneth Faried': 84, 'Dante Cunningham': 85, 'James Young': 79, 'Terry Rozier': 78, "E'Twaun Moore": 94, 'Derrick Favors': 82, 'Andre Roberson': 144, 'Adreian Payne': 110, 'Jahlil Okafor': 101, 'JaKarr Sampson': 102, 'Blake Griffin': 200, 'Nikola Mirotic': 162, 'Joffrey Lauvergne': 103, 'Cameron Payne': 108, 'Pat Connaughton': 109, 'John Henson': 176, 'Paul Millsap': 288, 'Jose Calderon': 114, 'Kristaps Porzingis': 98, 'Lou Williams': 99, 'Josh McRoberts': 96, 'Michael Kidd-Gilchrist': 97, 'Josh Huestis': 100, 'DeMarcus Cousins': 113, 'Marco Belinelli': 106, 'Ersan Ilyasova': 107, 'Andre Iguodala': 105, 'T.J. Warren': 300, 'Ben McLemore': 112, 'James Johnson': 141, 'Clint Capela': 115, 'Jimmy Butler': 117, 'Matthew Dellavedova': 128, 'Kemba Walker': 118, 'Dewayne Dedmon': 120, 'Darrell Arthur': 136, 'Noah Vonleh': 126, 'Thanasis Antetokounmpo': 119, 'Kentavious Caldwell-Pope': 137, 'Terrence Jones': 146, 'Manu Ginobili': 165, 'Sam Dekker': 116, 'Richaun Holmes': 123, 'Austin Rivers': 158, 'Tobias Harris': 140, 'Chris McCullough': 121, 'Ish Smith': 122, 'Allen Crabbe': 124, 'Kevin Love': 125, 'Trey Burke': 129, 'Marc Gasol': 229, 'Anthony Brown': 134, 'Willie Reed': 188, 'Kyle Anderson': 127, 'Nerlens Noel': 130, 'Jason Smith': 135, 'Reggie Bullock Jr.': 138, 'Reggie Jackson': 139, 'Spencer Dinwiddie': 180, 'Kelly Olynyk': 179, 'Kawhi Leonard': 147, 'Nemanja Bjelica': 172, 'Lance Stephenson': 142, 'Brandan Wright': 132, 'CJ Miles': 143, 'Andrew Bogut': 145, 'Iman Shumpert': 150, 'Shabazz Napier': 153, 'JaVale McGee': 160, 'Tyson Chandler': 148, 'Anthony Tolliver': 170, 'Omer Asik': 164, 'T.J. McConnell': 149, 'Stanley Johnson': 171, 'Udonis Haslem': 156, 'LeBron James': 154, 'Arron Afflalo': 157, 'Evan Fournier': 161, 'Kyle Lowry': 159, 'Jarell Eddie': 155, 'Michael Carter-Williams': 305, 'Luc Mbah a Moute': 174, 'Seth Curry': 294, 'Taj Gibson': 163, 'Jordan Clarkson': 166, 'Joe Young': 175, 'Kosta Koufos': 167, 'Danny Green': 257, 'Joel Embiid': 278, 'Luke Babbitt': 168, 'Zach Randolph': 185, 'Nikola Vucevic': 205, 'Bobby Portis': 429, 'Timofey Mozgov': 169, 'Mario Chalmers': 424, 'Jonathon Simmons': 182, 'Robert Covington': 194, 'Vince Carter': 184, 'Mike Scott': 173, 'Brandon Jennings': 177, 'Wayne Ellington': 178, 'Jae Crowder': 204, 'Gordon Hayward': 187, 'DeMar DeRozan': 181, 'Jonas Valanciunas': 183, 'Meyers Leonard': 404, 'Jonas Jerebko': 191, 'Kent Bazemore': 186, 'Patrick Patterson': 198, 'Serge Ibaka': 189, 'Jeff Green': 195, 'Brook Lopez': 192, 'Kyle Singler': 199, 'Ryan Anderson': 327, 'Eric Moreland': 190, 'Boban Marjanovic': 196, 'Marvin Williams': 197, 'Rondae Hollis-Jefferson': 193, 'Paul George': 263, 'Jrue Holiday': 201, 'Terrence Ross': 203, 'Patty Mills': 325, 'Nick Young': 202, 'Shaun Livingston': 296, 'David West': 206, 'Lorenzo Brown': 213, 'Chris Paul': 231, 'JJ Redick': 207, 'Bojan Bogdanovic': 350, 'Thaddeus Young': 338, 'Khris Middleton': 214, 'Evan Turner': 211, 'Darren Collison': 208, 'Ian Clark': 210, 'Jamal Crawford': 458, 'Russell Westbrook': 472, 'John Wall': 255, 'Wesley Johnson': 215, 'Aaron Gordon': 218, 'Isaiah Canaan': 332, 'Alec Burks': 212, 'Aaron Harrison': 216, 'J.J. Barea': 217, 'JR Smith': 221, 'Andre Drummond': 266, 'Jodie Meeks': 219, 'John Holland': 222, 'Isaiah Thomas': 220, 'Lucas Nogueira': 226, 'Darrun Hilliard': 223, 'Anderson Varejao': 224, 'Briante Weber': 225, 'Jordan McRae': 227, 'Frank Kaminsky': 228, 'Ben Simmons': 419, 'Denzel Valentine': 312, 'Gary Harris': 250, 'Brice Johnson': 337, 'Okaro White': 375, 'Chasson Randle': 357, 'Aron Baynes': 230, 'Alex Abrines': 334, 'Marcus Smart': 240, 'Michael Beasley': 304, 'Kay Felder': 235, 'Caris LeVert': 289, 'Aaron Brooks': 238, 'Tim Quarterman': 256, 'Marshall Plumlee': 272, 'Dejounte Murray': 236, 'Damian Jones': 233, 'Tony Snell': 234, 'Georgios Papagiannis': 249, 'Skal Labissiere': 237, 'Ivica Zubac': 242, 'Georges Niang': 232, 'Chinanu Onuaku': 244, 'Derrick Jones Jr.': 269, 'Jerian Grant': 239, 'Danuel House Jr.': 251, 'Ron Baker': 241, 'Patrick McCaw': 254, 'Devin Booker': 243, 'Ricky Rubio': 260, 'Doug McDermott': 245, 'Will Barton': 271, 'Davis Bertans': 248, 'Al Horford': 267, 'Christian Wood': 253, 'Willy Hernangomez': 247, 'Jason Terry': 252, 'DeAndre Liggins': 262, 'Wilson Chandler': 259, 'Henry Ellenson': 264, 'Malachi Richardson': 298, 'Al-Farouq Aminu': 287, 'Isaiah Whitehead': 261, 'Bryn Forbes': 258, 'Shabazz Muhammad': 270, 'Zach LaVine': 265, 'Quincy Acy': 341, 'Treveon Graham': 273, 'Troy Daniels': 268, 'Rashad Vaughn': 276, 'Demetrius Jackson': 290, 'Paul Zipser': 284, 'Timothe Luwawu-Cabarrot': 275, 'Myles Turner': 274, 'Kyle Korver': 277, 'Julius Randle': 280, 'Juancho Hernangomez': 282, 'Dion Waiters': 308, 'Bobby Brown': 281, 'Jared Dudley': 283, "DeAndre' Bembry": 285, 'Derrick Williams': 286, 'Nikola Jokic': 292, 'Yogi Ferrell': 291, 'Rodney McGruder': 306, 'Jamal Murray': 454, 'Malik Beasley': 293, 'Maurice Harkless': 295, "Kyle O'Quinn": 297, 'Gerald Green': 301, 'Deyonta Davis': 316, 'Tim Frazier': 299, 'Wade Baldwin IV': 307, 'Solomon Hill': 488, 'Cory Joseph': 303, 'Kelly Oubre Jr.': 302, 'Dante Exum': 310, 'Troy Williams': 309, 'Taurean Prince': 313, 'Tyler Zeller': 328, 'Joel Bolomboy': 344, 'JaMychal Green': 311, 'Raul Neto': 321, 'Cheick Diallo': 314, 'Giannis Antetokounmpo': 315, 'Mindaugas Kuzminskas': 317, 'Nicolas Brussino': 323, 'Klay Thompson': 318, 'Tomas Satoransky': 322, 'Amir Johnson': 319, 'Jaylen Brown': 320, 'Joe Johnson': 324, 'Mike Muscala': 330, 'Ed Davis': 326, 'Dragan Bender': 333, 'D.J. Augustin': 331, 'Enes Freedom': 339, 'Richard Jefferson': 329, 'Garrett Temple': 342, 'Ramon Sessions': 503, "Johnny O'Bryant III": 360, 'Kris Dunn': 335, 'Jabari Parker': 358, 'Eric Bledsoe': 336, 'Axel Toupane': 340, 'Isaiah Taylor': 352, 'Shelvin Mack': 348, 'Malcolm Brogdon': 345, 'Jarrod Uthoff': 346, 'Sean Kilpatrick': 349, 'Alan Williams': 347, 'Glenn Robinson III': 477, 'Brandon Ingram': 351, 'Andrew Harrison': 353, 'Malcolm Delaney': 356, 'James Harden': 355, 'Tristan Thompson': 362, 'Pascal Siakam': 363, 'Dennis Schroder': 359, 'Trevor Ariza': 361, 'Dario Saric': 432, 'Gary Payton II': 405, 'Jeff Withey': 364, 'Justin Patton': 478, 'Frank Jackson': 530, 'OG Anunoby': 487, 'Harry Giles III': 540, 'Davon Reed': 450, 'Ante Zizic': 373, 'Guerschon Yabusele': 367, 'Jabari Bird': 365, 'Kadeem Allen': 433, 'Wayne Selden': 393, 'Bogdan Bogdanovic': 380, 'Chris Boucher': 486, 'Quinn Cook': 372, 'Furkan Korkmaz': 387, 'Zach Collins': 366, 'Kobi Simmons': 374, 'Derrick Walton Jr.': 396, 'Mangok Mathiang': 378, 'Marcus Paige': 489, 'Tony Bradley': 382, 'Jack Cooley': 411, 'Jamel Artis': 438, 'Khem Birch': 377, 'Wes Iwundu': 369, 'Johnathan Motley': 431, 'Monte Morris': 436, 'Torrey Craig': 421, 'Tyler Lydon': 413, 'Alex Poythress': 370, 'Edmond Sumner': 499, 'Ike Anigbogu': 371, 'Dwight Buycks': 385, 'Matt Costello': 386, 'Devin Robinson': 391, 'C.J. Williams': 400, 'Jawun Evans': 381, 'Luke Kornet': 469, 'Josh Hart': 368, 'Thomas Bryant': 394, 'Vander Blue': 395, 'Malcolm Miller': 443, 'Daniel Hamilton': 408, 'PJ Dozier': 470, 'Nate Wolters': 376, 'Dennis Smith Jr.': 379, 'Frank Ntilikina': 384, 'Isaiah Hicks': 468, 'Milos Teodosic': 435, 'Alex Caruso': 442, 'Julyan Stone': 422, 'Alec Peters': 402, 'Antonio Blakeney': 383, 'Markelle Fultz': 490, 'Dorian Finney-Smith': 397, 'Jordan Bell': 389, 'Ryan Arcidiacono': 455, 'Luke Kennard': 392, 'Greg Monroe': 410, 'Jonathan Isaac': 388, 'Ivan Rabb': 390, 'Charles Cooke': 406, 'Jalen Jones': 407, 'Jarrett Allen': 403, 'Josh Magette': 416, 'David Nwaba': 423, 'T.J. Leaf': 398, 'Alfonzo McKinnie': 399, 'Derrick White': 428, 'Domantas Sabonis': 401, 'Sterling Brown': 414, 'Cole Aldrich': 409, 'Gorgui Dieng': 412, 'Tyler Dorsey': 417, 'Buddy Hield': 415, 'Shane Larkin': 418, 'D.J. Wilson': 420, 'Zhou Qi': 437, 'Kyle Kuzma': 427, 'Caleb Swanigan': 426, 'John Collins': 439, 'Justin Jackson': 434, 'Dakari Johnson': 430, 'Lauri Markkanen': 440, "De'Aaron Fox": 441, 'Donovan Mitchell': 444, 'Milton Doyle': 445, 'Erik McCree': 466, 'Damyean Dotson': 446, 'Lonzo Ball': 449, 'Semi Ojeleye': 448, 'Brandon Paul': 447, 'Frank Mason III': 475, 'Marquese Chriss': 460, 'Josh Jackson': 451, 'Ben Moore': 457, 'Andrew White III': 473, 'Abdel Nader': 452, 'Myke Henry': 453, 'James Webb III': 461, 'Fred VanVleet': 456, 'Markel Brown': 463, 'Reggie Hearn': 467, 'Tyler Cavanaugh': 485, 'Xavier Munford': 465, 'Channing Frye': 459, 'Nigel Hayes': 462, 'Cedi Osman': 464, 'Mason Plumlee': 476, 'Larry Drew II': 1035, 'Amile Jefferson': 479, 'Marcus Georges-Hunt': 471, 'Tyler Ulis': 474, 'Robin Lopez': 483, 'Antonius Cleveland': 496, 'Daniel Theis': 480, 'Tyrone Wallace': 491, 'Dwayne Bacon': 481, 'Emeka Okafor': 482, 'Terrance Ferguson': 484, 'Jaylen Morris': 1036, 'Thon Maker': 495, 'Bam Adebayo': 493, 'Dwight Powell': 492, 'Travis Wear': 494, 'MarShon Brooks': 497, 'Jayson Tatum': 498, 'David Stockton': 500, 'Kendrick Perkins': 502, 'Jake Layman': 501, 'Zhaire Smith': 559, 'Robert Williams III': 505, 'Jarred Vanderbilt': 551, 'Damion Lee': 510, 'Trevon Duval': 1037, 'Yuta Watanabe': 512, "Devonte' Graham": 506, 'Melvin Frazier Jr.': 507, 'Kostas Antetokounmpo': 550, 'Michael Porter Jr.': 609, 'Alize Johnson': 504, 'Lonnie Walker IV': 542, "De'Anthony Melton": 509, 'Gary Trent Jr.': 516, 'Moritz Wagner': 511, 'Omari Spellman': 508, 'Kevin Knox II': 518, 'Shake Milton': 521, 'Rodions Kurucs': 515, 'Jaylen Adams': 513, 'Bismack Biyombo': 529, 'Andrew Wiggins': 514, 'Darius Miller': 517, 'Dzanan Musa': 523, 'Bruce Brown': 519, 'Jacob Evans': 520, 'Jakob Poeltl': 522, 'Dillon Brooks': 539, 'Donte DiVincenzo': 527, 'Jonah Bolden': 533, 'Mario Hezonja': 524, 'Jevon Carter': 525, 'Chandler Hutchison': 526, 'Hamidou Diallo': 528, 'Jerome Robinson': 538, 'Maxi Kleber': 532, 'Marvin Bagley III': 534, 'Luka Doncic': 531, 'Isaiah Hartenstein': 535, 'Anfernee Simons': 536, 'Allonzo Trier': 541, 'Mitchell Robinson': 547, 'Ryan Broekhoff': 537, 'Grayson Allen': 545, 'Keita Bates-Diop': 543, 'Kevin Huerter': 544, 'Mo Bamba': 548, 'Trey Lyles': 546, 'Wendell Carter Jr.': 624, 'Khyri Thomas': 549, 'Deandre Ayton': 552, 'Jaren Jackson Jr.': 553, 'Troy Brown Jr.': 554, 'Svi Mykhailiuk': 557, 'Karl-Anthony Towns': 555, 'Brad Wanamaker': 556, 'Ekpe Udoh': 558, 'Landry Shamet': 560, 'Dylan Windler': 666, 'Zion Williamson': 606, 'Amir Coffey': 566, 'Romeo Langford': 565, 'Tacko Fall': 562, 'Sekou Doumbouya': 577, 'Cameron Johnson': 564, 'Ty Jerome': 584, 'Adam Mokoka': 597, 'Max Strus': 576, 'Shaquille Harrison': 561, 'Nic Claxton': 567, 'Bol Bol': 571, 'Jordan Bone': 563, 'Michael Frazier II': 603, 'Jalen Lecque': 595, 'Naz Reid': 575, 'Alen Smailagic': 580, 'Isaiah Roby': 600, 'Jared Harper': 615, 'Trae Young': 568, 'KZ Okpala': 590, 'Vlatko Cancar': 588, 'Goga Bitadze': 573, 'Brandon Clarke': 569, 'Eric Paschall': 570, 'Tyler Herro': 572, 'Josh Okogie': 574, 'Nigel Williams-Goss': 581, 'Cam Reddish': 578, 'Dewan Hernandez': 582, 'RJ Barrett': 579, 'Naz Mitrou-Long': 605, 'Matt Thomas': 601, 'Chimezie Metu': 583, 'Juwan Morgan': 585, 'Ja Morant': 589, 'Kenrich Williams': 586, "De'Andre Hunter": 587, 'Malik Monk': 591, 'Nassir Little': 593, 'Daniel Gafford': 592, 'P.J. Washington': 596, 'Vincent Poirier': 604, 'Terance Mann': 599, 'Rui Hachimura': 616, 'Jarrett Culver': 594, 'Matisse Thybulle': 602, 'Jordan Poole': 598, 'Kevin Porter Jr.': 610, 'Bruno Fernando': 617, 'Garrison Mathews': 614, 'Gabe Vincent': 611, 'Dean Wade': 607, 'Anzejs Pasecniks': 608, 'Kendrick Nunn': 613, 'Javonte Green': 612, 'Marko Guduric': 618, 'Kyle Alexander': 623, 'Cody Martin': 619, 'Darius Bazley': 627, 'Deonte Burton': 620, 'Jaylen Nowell': 621, 'Norvel Pelle': 622, 'Jalen Brunson': 663, 'Ky Bowman': 625, 'Darius Garland': 669, 'Oshae Brissett': 629, 'Tremont Waters': 636, 'Shai Gilgeous-Alexander': 626, 'Kelan Martin': 741, 'Jontay Porter': 684, 'Isaac Bonga': 628, 'Elie Okobo': 631, "Royce O'Neale": 630, 'Chris Chiozza': 632, 'Donta Hall': 633, 'Luguentz Dort': 634, 'Chris Silva': 637, 'Vic Law': 635, 'Wenyen Gabriel': 644, 'Brian Bowen II': 662, 'Chris Clemons': 670, 'Jay Scrubb': 681, 'Killian Tillie': 661, 'Xavier Tillman': 642, 'Grant Riller': 639, 'DaQuan Jeffries': 689, 'Quinndary Weatherspoon': 678, 'Devon Dotson': 640, 'Onyeka Okongwu': 660, 'Trent Forrest': 646, 'KJ Martin': 643, 'Jordan McLaughlin': 638, 'Mamadi Diakite': 698, 'Immanuel Quickley': 641, 'Obi Toppin': 658, 'Isaac Okoro': 645, 'Jalen Smith': 648, 'Mason Jones': 653, 'Tyrese Haliburton': 647, 'Chuma Okeke': 683, 'Sindarius Thornwell': 652, 'Sam Merrill': 650, 'Aleksej Pokusevski': 654, 'John Konchar': 656, 'Nick Richards': 649, 'Killian Hayes': 713, 'Collin Sexton': 665, 'Reggie Perry': 651, 'Drew Eubanks': 677, 'Grant Williams': 659, 'Joe Ingles': 655, 'Brodric Thomas': 664, "Jahmi'us Ramsey": 657, 'Carsen Edwards': 671, 'CJ Elleby': 672, 'Luka Samanic': 667, 'Elijah Hughes': 693, 'Patrick Williams': 668, 'Deni Avdija': 682, 'Josh Hall': 680, 'Aaron Nesmith': 673, 'Markus Howard': 676, 'Payton Pritchard': 685, 'Keljin Blevins': 674, 'Lamar Stevens': 675, 'Nate Darling': 679, 'Jalen McDaniels': 691, 'Sean McDermott': 690, 'Naji Marshall': 686, 'Robert Woodard II': 704, 'Udoka Azubuike': 725, 'James Wiseman': 695, 'Jordan Nwora': 700, 'Tyrell Terry': 694, 'Theo Maledon': 687, 'Facundo Campazzo': 688, 'Cole Anthony': 715, 'Caleb Martin': 696, 'Anthony Gill': 692, 'Daniel Oturu': 1038, 'Nathan Knight': 1039, 'Saben Lee': 763, 'Devin Vassell': 699, 'Keldon Johnson': 697, 'R.J. Hampton': 706, 'Malachi Flynn': 705, 'Zeke Nnaji': 701, 'Mfiondu Kabengele': 702, 'Jaden McDaniels': 703, 'Brandon Goodwin': 707, 'LaMelo Ball': 723, 'Ignas Brazdeikis': 710, 'Nicolo Melli': 708, 'Gary Clark': 711, 'Paul Watson': 719, 'Jaxson Hayes': 709, 'Coby White': 712, 'Tyrese Maxey': 714, 'Kira Lewis Jr.': 716, 'Armoni Brooks': 717, 'Juan Toscano-Anderson': 718, 'Gabriel Deck': 722, 'Paul Reed': 721, 'Myles Powell': 720, 'Devin Cannady': 724, 'Didi Louzada': 829, 'Miles Bridges': 728, "Jae'Sean Tate": 726, 'Talen Horton-Tucker': 727, 'Aaron Holiday': 775, 'Omer Yurtseven': 729, 'Deividas Sirvydis': 1040, 'Ty-Shon Alexander': 730, 'Jonathan Kuminga': 737, "Day'Ron Sharpe": 731, 'Cade Cunningham': 736, 'Isaiah Livers': 739, 'Devontae Cacok': 745, 'Cassius Winston': 750, 'Trendon Watford': 756, 'Keon Johnson': 740, 'Yves Pons': 751, 'Scottie Lewis': 778, 'Louis King': 732, 'Neemias Queta': 773, 'Jason Preston': 1041, 'Eugene Omoruyi': 734, 'Sam Hauser': 765, 'Malik Fitts': 733, 'David Duke Jr.': 774, 'Kessler Edwards': 759, 'McKinley Wright IV': 766, 'Marko Simonovic': 753, 'RJ Nembhard Jr.': 747, 'Jaden Springer': 744, 'Miye Oni': 735, 'Marcus Garrett': 760, 'Vernon Carey Jr.': 738, 'Brandon Boston': 742, 'Isaiah Jackson': 757, 'Scottie Barnes': 743, 'Herbert Jones': 749, 'Isaiah Joe': 755, 'Sandro Mamukelashvili': 768, 'Isaiah Todd': 746, 'Ziaire Williams': 748, 'Terence Davis': 754, 'Austin Reaves': 769, 'Alperen Sengun': 752, 'Jock Landale': 767, 'Precious Achiuwa': 764, 'Greg Brown III': 758, 'Jalen Suggs': 761, 'Chris Duarte': 762, 'Evan Mobley': 770, 'JT Thor': 772, 'Bones Hyland': 771, 'Jalen Green': 786, 'Usman Garuba': 780, 'Jericho Sims': 776, 'Kai Jones': 777, 'Josh Giddey': 779, 'David Johnson': 806, 'Ayo Dosunmu': 784, 'Jared Butler': 782, 'Quentin Grimes': 785, 'Dalano Banton': 781, 'Jose Alvarado': 783, 'Santi Aldama': 793, 'Davion Mitchell': 790, 'Anthony Edwards': 796, 'Miles McBride': 789, 'Josh Green': 787, 'Justin Champagnie': 794, 'Mychal Mulder': 802, 'Sharife Cooper': 799, 'Cam Thomas': 791, 'Isaiah Stewart': 809, 'Moses Moody': 792, 'Jalen Johnson': 812, 'BJ Johnson': 788, 'Ish Wainright': 795, 'Tre Mann': 804, 'Moses Wright': 797, 'Jeremiah Robinson-Earl': 807, 'Matt Mooney': 798, 'Zylan Cheatham': 801, 'Brandon Williams': 808, 'Duncan Robinson': 805, 'Malcolm Hill': 800, 'Jaylen Hoard': 803, 'Tyler Cook': 817, 'Olivier Sarr': 810, 'Scotty Hopson': 811, 'Xavier Moon': 814, 'Desmond Bane': 813, 'Leandro Bolmaro': 815, 'Tre Jones': 818, 'Langston Galloway': 816, 'Vit Krejci': 822, 'Luka Garza': 819, 'Lindell Wigginton': 820, 'Trey Murphy III': 821, 'Jamorko Pickett': 823, 'Aaron Wiggins': 826, 'James Bouknight': 824, 'Terry Taylor': 825, 'Theo Pinson': 833, 'Joshua Primo': 827, 'Joe Wieskamp': 828, 'Skylar Mays': 831, 'Anthony Lamb': 1042, 'Duane Washington Jr.': 830, 'Admiral Schofield': 834, 'Franz Wagner': 832, 'Nate Hinton': 876, 'Charles Bassey': 835, 'Chaundee Brown Jr.': 1043, 'E.J. Liddell': 1024, 'Chet Holmgren': 1012, 'Collin Gillespie': 996, 'Daishen Nix': 836, 'TyTy Washington Jr.': 906, 'Corey Kispert': 841, 'Cole Swider': 847, 'Jaden Ivey': 837, 'Walker Kessler': 839, 'Jake LaRavia': 838, 'AJ Green': 844, 'Jeremy Sochan': 840, 'Jalen Duren': 843, 'Blake Wesley': 858, 'Mark Williams': 842, 'Patrick Baldwin Jr.': 846, 'Paolo Banchero': 848, 'Malaki Branham': 864, 'Keegan Murray': 845, 'Saddiq Bey': 850, 'Max Christie': 928, 'Andrew Nembhard': 851, 'Peyton Watson': 849, 'JD Davison': 944, 'Johnny Juzang': 857, 'Chima Moneke': 853, 'Johnny Davis': 852, 'MarJon Beauchamp': 854, 'Alondes Williams': 855, 'John Butler Jr.': 1044, 'Vince Williams Jr.': 856, 'Kendall Brown': 1045, 'Ousmane Dieng': 920, 'Moussa Diabate': 860, 'Simone Fontecchio': 859, 'Jabari Smith Jr.': 861, 'Dyson Daniels': 863, 'Micah Potter': 976, 'Jack White': 867, 'Orlando Robinson': 862, 'Ryan Rollins': 907, 'Ibou Badji': 916, 'Kennedy Chandler': 1046, 'Jalen Williams': 865, 'Bennedict Mathurin': 866, 'Nikola Jovic': 872, 'Lindy Waters III': 868, 'Matt Ryan': 869, 'Kevon Harris': 870, 'Shaedon Sharpe': 871, 'Jaylin Williams': 880, 'Trevor Keels': 1047, 'Christian Koloko': 917, 'Tari Eason': 882, 'Jalen Hood-Schifino': 886, 'Jay Huff': 877, 'Haywood Highsmith': 878, 'Bryce McGowens': 873, 'Jalen Slawson': 874, 'Jaden Hardy': 875, 'Dariq Whitehead'

In [95]:
id_table['pst_ID'] = None
for index, row in id_table.iterrows():
    try:
        id_table.loc[index, 'pst_ID'] = pst_name_id[row['athlete']]
    except:
        id_table.loc[index, 'pst_ID'] = -1

id_table

      Unnamed: 0  hoopR_ID          athlete  nba_api_ID pst_ID
0              0       136     Vince Carter        1713    184
1              1       165   Jamal Crawford        2037    458
2              2       272    Manu Ginobili        1938    165
3              3       609    Dirk Nowitzki        1717     33
4              4       841      Jason Terry        1891    252
...          ...       ...              ...         ...    ...
1194        1194   4277916  RJ Nembhard Jr.     1630612    747
1195        1195   5211176   Tidjane Salaun     1642275    982
1196        1196   3102532   Vasilije Micic      203995    946
1197        1197   4578893       Vit Krejci     1630249    822
1198        1198   4230557    Vlatko Cancar     1628427    588

[1199 rows x 5 columns]

In [97]:
#this result matches what we see on pst and roughly matches injuries reported on fox sports
df[df['player_id'] == 9].head(45)

,Date,Team,Acquired,Relinquished,Notes,player_id
42,2016-01-02,Warriors,Stephen Curry,NaN,returned to lineup,9
830,2016-03-01,Warriors,NaN,Stephen Curry,left ankle injury (DTD),9
853,2016-03-03,Warriors,Stephen Curry,NaN,returned to lineup,9
1608,2016-04-16,Warriors,NaN,Stephen Curry,sprained right ankle (DTD),9
1638,2016-04-18,Warriors,NaN,Stephen Curry,placed on IL with sprained right ankle,9
1668,2016-04-24,Warriors,Stephen Curry,NaN,activated from IL,9
1674,2016-04-25,Warriors,NaN,Stephen Curry,sprained MCL in right knee (DTD),9
1687,2016-04-27,Warriors,NaN,Stephen Curry,placed on IL with sprained MCL in right knee,9
1706,2016-05-09,Warriors,Stephen Curry,NaN,activated from IL,9
3461,2017-01-29,Warriors,NaN,Stephen Curry,placed on IL with stomach flu,9
3517,2017-02-01,Warriors,Stephen Curry,NaN,activated from IL,9
4026,2017-03-11,Warriors,NaN,Stephen Curry,rest (DTD),9
4075,2017-03-14,Warriors,Stephen Curry,NaN,returned to lineup,9
4544,2017-04-08,Warriors,NaN,Stephen Curry,bruised left knee (DTD),9
4602,2017-04-10,Warriors,Stephen Curry,NaN,returned to lineup,9
5422,2017-11-13,Warriors,NaN,Stephen Curry,placed on IL with bruised right thigh,9
5481,2017-11-16,Warriors,Stephen Curry,NaN,activated from IL,9
5655,2017-11-27,Warriors,NaN,Stephen Curry,placed on IL with bruised right hand,9
5693,2017-11-29,Warriors,Stephen Curry,NaN,activated from IL,9
5809,2017-12-05,Warriors,NaN,Stephen Curry,sprained right ankle (DTD),9
5827,2017-12-06,Warriors,NaN,Stephen Curry,placed on IL with sprained right ankle,9
6304,2017-12-30,Warriors,Stephen Curry,NaN,activated from IL,9
6458,2018-01-10,Warriors,NaN,Stephen Curry,sprained right ankle (DTD),9
6511,2018-01-13,Warriors,Stephen Curry,NaN,activated from IL,9
7334,2018-03-09,Warriors,NaN,Stephen Curry,placed on IL with sprained right ankle,9
7611,2018-03-23,Warriors,Stephen Curry,NaN,activated from IL,9
7628,2018-03-24,Warriors,NaN,Stephen Curry,sprained MCL in left knee (out indefinitely),9
7644,2018-03-25,Warriors,NaN,Stephen Curry,placed on IL with sprained MCL in left knee,9
8155,2018-05-01,Warriors,Stephen Curry,NaN,activated from IL,9
8512,2018-11-09,Warriors,NaN,Stephen Curry,strained left groin (out indefinitely),9
8526,2018-11-10,Warriors,NaN,Stephen Curry,placed on IL with strained left groin,9
8787,2018-12-01,Warriors,Stephen Curry,NaN,activated from IL,9
10325,2019-03-23,Warriors,NaN,Stephen Curry,placed on IL,9
10337,2019-03-24,Warriors,Stephen Curry,NaN,activated from IL,9
10605,2019-04-10,Warriors,NaN,Stephen Curry,placed on IL with sprained right ankle,9
10620,2019-04-12,Warriors,Stephen Curry,NaN,activated from IL,9
10856,2019-10-31,Warriors,NaN,Stephen Curry,fractured left hand (out indefinitely),9
10865,2019-11-01,Warriors,NaN,Stephen Curry,placed on IL with fractured left hand,9
12536,2020-03-04,Warriors,Stephen Curry,NaN,activated from IL,9
12579,2020-03-07,Warriors,NaN,Stephen Curry,placed on IL with flu,9
12647,2020-03-11,Warriors,Stephen Curry,NaN,activated from IL,9
13962,2021-02-20,Warriors,NaN,Stephen Curry,illness (DTD),9
13996,2021-02-23,Warriors,Stephen Curry,NaN,returned to lineup,9
14316,2021-03-19,Warriors,NaN,Stephen Curry,bruised tailbone (DTD),9
14379,2021-03-23,Warriors,NaN,Stephen Curry,placed on IL with bruised tailbone,9

In [99]:
df.shape

(25980, 6)

In [101]:
test = df[df['Relinquished'].isnull()]
test = test[test['Acquired'].isnull()]
test.head()

,Date,Team,Acquired,Relinquished,Notes,player_id
10217,2019-03-16,Nets,NaN,NaN,activated from IL,None
16466,2021-12-07,Blazers,NaN,NaN,collapsed right lung (out indefinitely),None
24046,2024-06-28,Pacers,NaN,NaN,NaN,None
24959,2024-12-23,NaN,NaN,NaN,NaN,None
26724,2025-04-02,Knicks,NaN,NaN,activated from IL,None

In [157]:
#analysis concludes that the records from the Nets is just a meaningless duplicate
df.drop(10217, axis=0, inplace=True)

#blazers record: duplicate for CJ McCollum
df.drop(16466, axis=0, inplace=True)

#the pacers record is Jalen Smith be activated from the injury list in a trade to the Chicago bulls
df.loc[24046, 'Acquired'] = 'Jalen Smith'
df.loc[24046, 'Notes'] = 'activated from IL'
df.loc[24046, 'player_id'] = 648

#just delete the last one because there is no information to go off of except the date.
df.drop(24959, axis=0, inplace=True)

#Kevin McCullar Jr but he was activated slightly before so just a duplicate
df.drop(26724, axis=0, inplace=True)

In [159]:
test = df[df['Relinquished'].isnull()]
test = test[test['Acquired'].isnull()]
test.head()

Empty DataFrame
Columns: [Date, Team, Acquired, Relinquished, Notes, player_id]
Index: []

In [163]:
test = df[df['Relinquished'].notnull()]
test = test[test['Acquired'].notnull()]
test.head()

,Date,Team,Acquired,Relinquished,Notes,player_id
7599,2018-03-23,Hawks,John Collins,John Collins,returned to lineup,439

In [165]:
#easy fix
df.loc[7599, 'Relinquished'] = df.loc[24046, 'Relinquished']

In [169]:
df.loc[7599, :]

Date                    2018-03-23
Team                         Hawks
Acquired              John Collins
Relinquished                   NaN
Notes           returned to lineup
player_id                      439
Name: 7599, dtype: object

In [171]:
path = "C:\\Users\\oscar\\big_ahh_files\\injuries.csv"
df.to_csv(path, index=False)

In [203]:
id_table.drop('Unnamed: 0', axis=1, inplace=True)

In [207]:
id_table.head()

   hoopR_ID         athlete  nba_api_ID pst_ID
0       136    Vince Carter        1713    184
1       165  Jamal Crawford        2037    458
2       272   Manu Ginobili        1938    165
3       609   Dirk Nowitzki        1717     33
4       841     Jason Terry        1891    252

In [209]:
path = "C:\\Users\\oscar\\OneDrive\\Desktop\\HON 492\\3IDs.csv"
id_table.to_csv(path, index=False)